[package]
name = "inillucent-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "SQLite-like shell used for compatibility testing and manual diagnosis."

[[bin]]
name = "inillucent-shell"
path = "src/main.rs"

[dependencies]
inillucent-alloc = { workspace = true }
inillucent-base = { workspace = true }
inillucent-scalar = { workspace = true }
inillucent-engine = { workspace = true }
inillucent-value = { workspace = true }
inillucent-tree = { workspace = true }
