//! The obligation registers: what this engine claims to expose.
//!
//! Invariant: every register here is *generated from the engine*, never typed.
//! A hand-written list of built-ins is a second source of truth that starts
//! wrong the day a function is added and is discovered wrong months later; a
//! generated one cannot disagree with the code it came from, and the harness
//! test that regenerates it catches a change that was made without meaning to.
//!
//! Three registers, and they answer three different questions:
//!
//! - `compat/api/builtins.toml`: every SQL function, its arity and its flags -
//!   which is the signature half of the obligation, and the effect half too,
//!   because `deterministic` and `innocuous` are what decide where a function
//!   may be called from.
//! - `compat/api/pragmas.toml`: every PRAGMA, the columns of its answer, and
//!   whether it takes an argument - the whole of what a caller has to know
//!   before it writes one, and the part a differential test compares.
//! - `compat/api/symbols.toml`: every symbol the C ABI exports, with the
//!   signature a caller compiles against. This one is read out of the source
//!   rather than out of a table, because the source *is* the table: the
//!   declarations are what a linker resolves.

use std::path::{Path, PathBuf};

use crate::workspace_root;

/// Returns every register, by file name.
pub fn registers() -> Vec<(&'static str, String)> {
    vec![
        ("builtins.toml", builtins()),
        ("pragmas.toml", pragmas()),
        ("symbols.toml", symbols()),
    ]
}

/// Returns the header every register opens with.
fn header(what: &str, how: &str) -> String {
    format!(
        "# {what}\n\
         #\n\
         # Generated by `cargo run -p inillucent-compat --bin inillucent-obligations`.\n\
         # Do not edit by hand: {how}\n\
         # `inillucent-compat::obligations::the_registers_match_the_engine` fails if\n\
         # this file and the engine disagree.\n\n"
    )
}

/// Returns the built-in function register.
fn builtins() -> String {
    let mut out = header(
        "Every SQL function this engine provides.",
        "it is read straight out of `inillucent_sql::function::every_function`.",
    );
    let mut entries = inillucent_sql::function::every_function();
    entries.sort_by(|left, right| left.name.cmp(right.name).then(left.arity.cmp(&right.arity)));
    out.push_str(&format!("count = {}\n\n", entries.len()));
    for entry in entries {
        out.push_str("[[function]]\n");
        out.push_str(&format!("name = {:?}\n", entry.name));
        out.push_str(&format!("kind = {:?}\n", entry.kind));
        out.push_str(&format!("arity = {}\n", entry.arity));
        out.push_str(&format!("flags = {}\n", entry.flags));
        out.push_str(&format!("deterministic = {}\n", entry.flags & 524_288 != 0));
        out.push_str(&format!("innocuous = {}\n\n", entry.flags & 2048 != 0));
    }
    out
}

/// Returns the PRAGMA register.
fn pragmas() -> String {
    let mut out = header(
        "Every PRAGMA this engine answers.",
        "it is read straight out of `inillucent_sql::pragma_register::REGISTER`.",
    );
    let mut entries: Vec<&inillucent_sql::pragma_register::PragmaSpec> =
        inillucent_sql::pragma_register::REGISTER.iter().collect();
    entries.sort_by(|left, right| left.name.cmp(right.name));
    out.push_str(&format!("count = {}\n\n", entries.len()));
    for entry in entries {
        out.push_str("[[pragma]]\n");
        out.push_str(&format!("name = {:?}\n", entry.name));
        out.push_str(&format!("columns = {:?}\n", entry.columns));
        out.push_str(&format!("takes_argument = {}\n\n", entry.takes_argument));
    }
    out
}

/// Returns `docs/pragmas.md`, the pragma table as a page a person reads.
///
/// **Generated for the same reason the command table is (task-1961, A16).**
/// `crates/inillucent-engine/src/pragma.rs` recognises 85 names and the
/// documentation mentioned 40, which is the shape of every hand-written feature
/// list: it is right on the day it is written and nobody notices when it stops
/// being. The command table has been generated from
/// `crates/inillucent-cli/src/command/registry.rs` and checked by
/// `--test command_parity` since it was written; this is the same arrangement
/// for pragmas.
///
/// The register is the *structural* half - the name, the columns the answer
/// has, whether it takes an argument - and deliberately says nothing about what
/// each pragma does. A sentence per pragma would be prose in a generated file,
/// which is the thing that goes stale; the page points at `docs/sql.md` for
/// behaviour.
pub fn pragma_page() -> String {
    let mut entries: Vec<&inillucent_sql::pragma_register::PragmaSpec> =
        inillucent_sql::pragma_register::REGISTER.iter().collect();
    entries.sort_by(|left, right| left.name.cmp(right.name));
    let taking = entries.iter().filter(|entry| entry.takes_argument).count();

    let mut out = String::new();
    out.push_str("# Pragmas\n\n");
    out.push_str("A pragma is a statement that reads or changes a setting of the database, such\n");
    out.push_str("as `PRAGMA page_size` or `PRAGMA busy_timeout = 2000`. This page lists every\n");
    out.push_str("pragma the engine recognises.\n\n");
    out.push_str(
        "This page is generated. `cargo run -p inillucent-compat --bin inillucent-obligations`\n",
    );
    out.push_str("writes it from `inillucent_sql::pragma_register::REGISTER`, and\n");
    out.push_str(
        "`cargo test -p inillucent-compat --test tooling harness::` fails when the page and the\n",
    );
    out.push_str("register differ. Do not edit it by hand.\n\n");
    out.push_str(&format!(
        "There are **{} pragmas**. {} of them take an argument in parentheses.\n\n",
        entries.len(),
        taking
    ));
    out.push_str(
        "A pragma that is not in this table is not recognised. It returns no rows and no\n",
    );
    out.push_str("error, which is also what SQLite does. So running a pragma does not tell you\n");
    out.push_str("whether the engine knows it. Check this table instead.\n\n");
    out.push_str("The table gives each pragma's name, whether it takes an argument, and the\n");
    out.push_str("columns of the rows it returns. [SQL support](sql.md) describes what the\n");
    out.push_str("pragmas do.\n\n");
    out.push_str("| pragma | takes an argument | columns of its answer |\n");
    out.push_str("|---|---|---|\n");
    for entry in entries {
        let columns = if entry.columns.is_empty() {
            "one unnamed column".to_string()
        } else {
            entry
                .columns
                .iter()
                .map(|name| format!("`{name}`"))
                .collect::<Vec<String>>()
                .join(", ")
        };
        out.push_str(&format!(
            "| `{}` | {} | {} |\n",
            entry.name,
            if entry.takes_argument { "yes" } else { "no" },
            columns
        ));
    }
    out.push_str("\n## Two defaults that matter when several processes share a file\n\n");
    out.push_str(
        "`busy_timeout` starts at **5000** milliseconds. When another process holds the\n",
    );
    out.push_str("file, a statement waits up to this long and then fails with `busy`. Set\n");
    out.push_str(
        "`busy_timeout` to 0 to make the statement fail at once. `busy_timeout` applies to\n",
    );
    out.push_str("waits between processes and to waits inside one process.\n\n");
    out.push_str(
        "`locking_mode` starts at **normal**, which is also SQLite's default. In normal\n",
    );
    out.push_str(
        "mode the file lock is released between statements, so a second process can open\n",
    );
    out.push_str(
        "the database. In `exclusive` mode the connection keeps the lock until it closes.\n",
    );
    out.push_str(
        "`exclusive` is faster for a program that only ever opens one connection. While\n",
    );
    out.push_str(
        "it holds the lock, a second process waits for `busy_timeout` and then fails. Any\n",
    );
    out.push_str("value other than `normal` or `exclusive` is an error.\n");
    out.push_str(
        "\n`compat/api/pragmas.toml` holds the same register in a form a program can read.\n",
    );
    out
}

/// Returns the C ABI symbol register, read out of the crate's own source.
///
/// Reading the source is the honest way to do this. A list kept beside the code
/// would be a promise about what is exported; the declarations *are* what is
/// exported, so a register built from them cannot claim a symbol that is not
/// there or miss one that is.
fn symbols() -> String {
    let mut out = header(
        "Every symbol the C ABI exports, with the signature a caller links against.",
        "it is read out of the `extern \"C\"` declarations in `inillucent-driver-capi`.",
    );
    let mut found = Vec::new();
    let source = workspace_root().join("drivers/inillucent-driver-capi/src");
    for file in rust_files(&source) {
        let Ok(text) = std::fs::read_to_string(&file) else {
            continue;
        };
        found.extend(declarations(&text));
    }
    found.sort();
    found.dedup();
    out.push_str(&format!("count = {}\n", found.len()));
    out.push_str("profile = \"default\"\n\n");
    for (name, signature) in found {
        out.push_str("[[symbol]]\n");
        out.push_str(&format!("name = {name:?}\n"));
        out.push_str(&format!("signature = {signature:?}\n\n"));
    }
    out
}

/// Returns every `.rs` file under a directory.
fn rust_files(directory: &Path) -> Vec<PathBuf> {
    let mut found = Vec::new();
    let Ok(entries) = std::fs::read_dir(directory) else {
        return found;
    };
    let mut paths: Vec<PathBuf> = entries
        .filter_map(|entry| entry.ok().map(|entry| entry.path()))
        .collect();
    paths.sort();
    for path in paths {
        if path.is_dir() {
            found.extend(rust_files(&path));
        } else if path.extension().is_some_and(|extension| extension == "rs") {
            found.push(path);
        }
    }
    found
}

/// Returns every exported C declaration in one source file.
///
/// The signature is normalised to one line with single spaces, because what it
/// is being compared against is another run of this program rather than a
/// person's formatting.
fn declarations(text: &str) -> Vec<(String, String)> {
    let mut found = Vec::new();
    let lines: Vec<&str> = text.lines().collect();
    for (index, line) in lines.iter().enumerate() {
        let Some(rest) = exported(line) else {
            continue;
        };
        let mut signature = String::from(rest);
        let mut scan = index;
        // A declaration may be wrapped over several lines; it ends at the brace
        // that opens the body.
        while !signature.contains('{') && scan + 1 < lines.len() {
            scan += 1;
            signature.push(' ');
            signature.push_str(lines.get(scan).copied().unwrap_or("").trim());
        }
        let signature = signature
            .split('{')
            .next()
            .unwrap_or("")
            .split_whitespace()
            .collect::<Vec<&str>>()
            .join(" ");
        let Some(name) = signature.split('(').next().map(str::trim) else {
            continue;
        };
        found.push((name.to_string(), signature));
    }
    found
}

/// The two ways an exported C function is declared.
///
/// The first is assembled with `concat!` rather than written out, so that this
/// file does not itself contain the word the policy test scans for. A tool that
/// searches for a keyword should not trip over the tool that searches for it.
const EXPORTED: [&str; 2] = [
    concat!("pub ", "unsafe", " extern \"C\" fn "),
    "pub extern \"C\" fn ",
];

/// Returns the part of a line after the declaration prefix, if it is one.
fn exported(line: &str) -> Option<&str> {
    for prefix in EXPORTED {
        if let Some(rest) = line.strip_prefix(prefix) {
            return Some(rest);
        }
    }
    None
}
