//! Generated predicates, graded against this engine's own answers.
//!
//! Invariant: **a predicate partitions a table into three parts and nothing
//! else.** For any predicate `P`, every row of a table satisfies exactly one of
//! `P`, `NOT P` and `P IS NULL`, so the three answers together are the table
//! and no row appears twice. That is true of SQL rather than of an engine, so
//! it can be checked without a second engine to compare against - which is the
//! point, because the pinned SQLite shares none of this engine's planner and so
//! cannot say whether *this* planner's route to a row is the route that finds
//! it.
//!
//! `new_engine_differential.rs` enumerates templates a person wrote, so it
//! finds the defects a person thought of. This generates predicate trees, which
//! is how the two arms below catch an optimiser defect nothing else here can:
//!
//! - **TLP** (ternary logic partitioning). `SELECT a FROM t` against
//!   `WHERE P` + `WHERE NOT P` + `WHERE P IS NULL`. A seek that skips a row the
//!   predicate matches shows up as a row missing from the union, and a range
//!   that admits a row twice shows up as a duplicate. Three-valued logic is
//!   what makes it work: `NOT P` is not "the rest", and an engine that treated
//!   it that way would lose every row where `P` is NULL.
//! - **NoREC** (non-optimising reference engine construction). The same
//!   predicate as a `WHERE`, which the planner may answer through an index,
//!   against the same predicate applied to every row of a scan. The second
//!   cannot use an index - there is no `WHERE` for the planner to push into one
//!   - so a disagreement is the index route answering something the row-by-row
//!   evaluation does not.
//!
//! Both arms run twice per case, before and after `ANALYZE`, because the
//! statistics are what make the planner choose a different route for the same
//! query and a suite that only ran one of them would only ever grade one route.
//!
//! ## What the arms after the first two are for (task-2066 §4.4.4)
//!
//! The first two grade the planner's route to a *row*. Everything above that -
//! the aggregate, the grouping, the join - was generated by nobody, so a defect
//! in one of them had only the hand-written templates to get past.
//!
//! - **Aggregate TLP.** `sum(a)` over the whole table against the sum of the
//!   three partitions' sums. An aggregate reads the same rows and then adds
//!   them, so a row admitted twice or skipped shows up in the total even when
//!   the row-returning arm is answered by a different plan.
//! - **`DISTINCT` and `GROUP BY` TLP.** The distinct values of a column are the
//!   union of the three partitions' distinct values, and each group's count is
//!   the sum of its count in each partition. Both are collapsing operators, and
//!   a collapse is where a duplicate stops being visible.
//! - **Join TLP**, over a second table whose join column is indexed **before**
//!   the rows are loaded. That is the ordinary order an application writes, and
//!   it is the one the read gate has never measured: every published figure is
//!   taken on a tree imported from SQLite, which is packed, so no figure has
//!   touched a leaf holding delta rows. §4.3.4 is about what that costs, and
//!   this is the arm that says the answers are right while it is fixed.
//! - **The recursive CTE arm**, for §4.1.1: a generated hierarchy with
//!   `ORDER BY depth DESC LIMIT k`, which is the shape that answered the root
//!   instead of the deepest node.
//!
//! **The corpus moves under the run.** Every fifty cases a range is deleted and
//! reinserted, so the tree has split and merged and its leaves hold delta rows
//! rather than a sorted run laid down once. A generator over a tree that was
//! built in order and never touched is grading one shape of page.
//!
//! **The depth is generated rather than fixed at two**, and the seed and the
//! depth are in every failure message, because a case that only reproduces at
//! depth four is one nobody can reproduce from a message that does not say so.

use std::path::PathBuf;

use inillucent_compat::facade::{Connection, Database};
use inillucent_value::Value;

/// How many predicates each test generates.
const CASES: usize = 400;

/// How many rows the table holds.
///
/// Enough that a seek and a scan are different plans, small enough that four
/// hundred predicates each run six queries over it in a few seconds.
const ROWS: i64 = 600;

/// Returns a scratch path nothing else in this file uses.
///
/// @param tag - what to name it after
fn scratch(tag: &str) -> PathBuf {
    let directory = PathBuf::from(env!("CARGO_TARGET_TMPDIR")).join("tlp");
    let _ = std::fs::create_dir_all(&directory);
    let path = directory.join(format!("{tag}.db"));
    let _ = std::fs::remove_file(&path);
    path
}

/// Returns the next value of a deterministic generator.
///
/// Written out rather than taken from a crate because the workspace's
/// dependency allow-list does not carry one, and a generator whose sequence is
/// fixed is what makes a failure here reproducible from the seed alone.
///
/// @param state - the generator's state, advanced in place
fn next(state: &mut u64) -> u64 {
    *state ^= *state << 13;
    *state ^= *state >> 7;
    *state ^= *state << 17;
    *state
}

/// Returns a number below a bound.
///
/// @param state - the generator's state
/// @param bound - one past the largest value wanted
fn below(state: &mut u64, bound: u64) -> u64 {
    match bound {
        0 => 0,
        bound => next(state) % bound,
    }
}

/// The columns a generated predicate may read.
///
/// One of each affinity, and `d` holds NULLs - which is what makes the `IS
/// NULL` partition non-empty and the whole TLP arm worth running.
const COLUMNS: &[&str] = &["a", "b", "c", "d"];

/// Returns a random comparison against one column.
///
/// @param state - the generator's state
fn atom(state: &mut u64) -> String {
    let column = COLUMNS
        .get((below(state, COLUMNS.len() as u64)) as usize)
        .copied()
        .unwrap_or("a");
    let operator = match below(state, 8) {
        0 => "=",
        1 => "<>",
        2 => "<",
        3 => "<=",
        4 => ">",
        5 => ">=",
        6 => "IS",
        _ => "IS NOT",
    };
    let value = match column {
        "b" => match below(state, 4) {
            0 => "NULL".to_string(),
            1 => "'k1'".to_string(),
            2 => format!("'k{}'", below(state, 40)),
            _ => format!("'{}'", below(state, 9)),
        },
        "c" => match below(state, 3) {
            0 => "NULL".to_string(),
            1 => format!("{}.5", below(state, 60)),
            _ => format!("{}", below(state, 600)),
        },
        _ => match below(state, 4) {
            0 => "NULL".to_string(),
            _ => format!("{}", below(state, 700)),
        },
    };
    // `IS` and `IS NOT` are the two that are not three-valued, and they are
    // generated on purpose: a partition that only ever held three-valued
    // comparisons would never exercise the arm where `P IS NULL` is empty.
    format!("{column} {operator} {value}")
}

/// Returns a comparison that is not a bare column against a constant.
///
/// **The atoms were all one shape** (task-2066 §4.4.4): a column, an operator
/// and a literal. A predicate built only out of those exercises the seek
/// planner and nothing else, so a defect in `LIKE`'s index handling, in a
/// collation, in an affinity conversion or in the arithmetic folded into a
/// bound had only the hand-written templates to get past.
///
/// Each of these is still a predicate over one row, so the partition rule holds
/// over them exactly as it does over the simple ones.
///
/// @param state - the generator's state
fn wide_atom(state: &mut u64) -> String {
    match below(state, 6) {
        // Text matching, which the planner may answer through `t_b` when the
        // pattern has a fixed prefix and may not when it does not.
        0 => format!("b LIKE 'k{}%'", below(state, 40)),
        1 => format!("b GLOB 'k{}*'", below(state, 10)),
        // A collation the column does not declare, which is a different
        // comparison from the one the index is ordered by.
        2 => format!("e COLLATE NOCASE = 'K{}'", below(state, 40)),
        // Arithmetic on the column side, which no index can be seeked on.
        3 => format!("(a % {}) = {}", below(state, 17) + 2, below(state, 3)),
        // An affinity conversion, where the comparison is between classes.
        4 => format!("CAST(c AS INTEGER) {} {}", ">=", below(state, 60)),
        _ => format!(
            "f {} x'{:02x}{:02x}'",
            "=",
            below(state, 256),
            below(state, 256)
        ),
    }
}

/// Returns a predicate tree of at most `depth` levels.
///
/// @param state - the generator's state
/// @param depth - how many more levels of AND, OR and NOT to allow
fn predicate(state: &mut u64, depth: u32) -> String {
    if depth == 0 {
        return atom(state);
    }
    match below(state, 7) {
        0 => format!(
            "({} AND {})",
            predicate(state, depth - 1),
            predicate(state, depth - 1)
        ),
        1 => format!(
            "({} OR {})",
            predicate(state, depth - 1),
            predicate(state, depth - 1)
        ),
        2 => format!("(NOT {})", predicate(state, depth - 1)),
        3 => {
            let column = COLUMNS
                .get((below(state, COLUMNS.len() as u64)) as usize)
                .copied()
                .unwrap_or("a");
            match column {
                "b" => format!("({column} IN ('k1', 'k2', 'k7', NULL))"),
                _ => format!(
                    "({column} IN ({}, {}, {}))",
                    below(state, 700),
                    below(state, 700),
                    below(state, 700)
                ),
            }
        }
        4 => {
            let low = below(state, 700);
            format!("(a BETWEEN {low} AND {})", low + below(state, 200))
        }
        5 => wide_atom(state),
        _ => atom(state),
    }
}

/// Runs a statement, returning its rows rendered or the failure's message.
///
/// @param connection - the database
/// @param sql - the statement
fn run(connection: &Connection, sql: &str) -> Result<Vec<String>, String> {
    let mut statement = connection
        .prepare(sql)
        .map_err(|failure| failure.message().to_string())?;
    let mut rows = Vec::new();
    loop {
        match statement.step() {
            Ok(true) => {}
            Ok(false) => break,
            Err(failure) => return Err(failure.message().to_string()),
        }
        let rendered: Vec<String> = statement
            .row()
            .iter()
            .map(|value| match value {
                Value::Null => "null".to_string(),
                Value::Integer(number) => format!("int:{number}"),
                Value::Real(number) => format!("real:{number:?}"),
                Value::Text(text) => {
                    format!("text:{}", String::from_utf8_lossy(&text.utf8_bytes()))
                }
                Value::Blob(blob) => format!("blob:{}", blob.raw().len()),
            })
            .collect();
        rows.push(rendered.join("|"));
    }
    Ok(rows)
}

/// Builds the table every case runs against.
///
/// @param connection - the database
fn build(connection: &Connection) {
    for statement in [
        // `e` and `f` are what the wide atoms read: a column whose index is
        // ordered by a different collation from the comparison, and a column of
        // bytes. Both are shapes the generator could not produce before
        // (task-2066 §4.4.4).
        "CREATE TABLE t(a INTEGER PRIMARY KEY, b TEXT, c REAL, d INTEGER, \
         e TEXT COLLATE NOCASE, f BLOB)",
        "CREATE INDEX t_b ON t(b)",
        "CREATE INDEX t_c ON t(c, a)",
        "CREATE INDEX t_d ON t(d)",
        "CREATE INDEX t_e ON t(e)",
        "BEGIN",
    ] {
        run(connection, statement).unwrap_or_else(|failure| panic!("{statement}: {failure}"));
    }
    for row in 1..=ROWS {
        // `d` is NULL every seventh row, which is what gives the `IS NULL`
        // partition rows to hold.
        let d = if row % 7 == 0 {
            "NULL".to_string()
        } else {
            format!("{}", row % 53)
        };
        let text = if row % 11 == 0 {
            "NULL".to_string()
        } else {
            format!("'k{}'", row % 40)
        };
        // `e` carries the same key in mixed case, so a NOCASE comparison and a
        // BINARY one disagree about it; `f` is two bytes that repeat every 256
        // rows and is NULL every thirteenth.
        let mixed = if row % 5 == 0 {
            format!("'K{}'", row % 40)
        } else {
            format!("'k{}'", row % 40)
        };
        let bytes = if row % 13 == 0 {
            "NULL".to_string()
        } else {
            format!("x'{:02x}{:02x}'", row % 256, (row / 7) % 256)
        };
        let sql = format!(
            "INSERT INTO t VALUES ({row}, {text}, {}, {d}, {mixed}, {bytes})",
            (row % 60) as f64 + 0.5
        );
        run(connection, &sql).unwrap_or_else(|failure| panic!("{sql}: {failure}"));
    }
    run(connection, "COMMIT").expect("the corpus commits");
}

/// Deletes a range of rows and puts them back, so the tree has moved.
///
/// **A corpus laid down once and never touched is one shape of page**
/// (task-2066 §4.4.4). Every leaf holds a sorted run written in order, which is
/// exactly the tree the read gate measures and exactly the tree an application
/// does not have. After this, leaves hold delta rows, the tree has split and
/// merged, and a probe into one has to merge before it can answer - which is
/// the path §4.3.4 is about.
///
/// Done entirely in SQL, through a holding table, rather than by reading the
/// rows out and writing them back: `run` renders a blob as its *length*, so a
/// round trip through this file's own rendering could not reproduce one. The
/// rows come back identical because the engine moves them, which is also what
/// makes this safe to do in the middle of a run - every arm compares against a
/// corpus that has not changed, over pages that have.
///
/// @param connection - the database
/// @param round - which mutation this is, which picks the range
fn churn(connection: &Connection, round: usize) {
    let width = 40i64;
    let low = ((round as i64).saturating_mul(width) % (ROWS - width)).max(1);
    let high = low + width;
    for sql in [
        format!("CREATE TABLE churn_held AS SELECT * FROM t WHERE a BETWEEN {low} AND {high}"),
        format!("DELETE FROM t WHERE a BETWEEN {low} AND {high}"),
        "INSERT INTO t SELECT * FROM churn_held".to_string(),
        "DROP TABLE churn_held".to_string(),
    ] {
        run(connection, &sql).unwrap_or_else(|failure| panic!("churn {round}: {sql}: {failure}"));
    }
    let back = run(connection, "SELECT count(*) FROM t").expect("the count reads back");
    assert_eq!(
        back.first().map(String::as_str),
        Some(format!("int:{ROWS}").as_str()),
        "the churn at round {round} did not put every row back"
    );
}

/// Returns a predicate depth in `1..=5`.
///
/// **Two was a constant** (task-2066 §4.4.4), so every predicate the generator
/// ever produced had the same shape of tree. A defect that needs three levels
/// of `OR` under a `NOT` was not reachable.
///
/// @param state - the generator's state
fn depth_of(state: &mut u64) -> u32 {
    (below(state, 5) + 1) as u32
}

/// A predicate and its negation and its NULL part are the whole table, once.
#[test]
fn a_predicate_partitions_the_table_into_three() {
    let path = scratch("partition");
    let database = Database::open(&path).expect("the database opens");
    let connection = database.session().expect("the connection opens");
    build(&connection);

    let whole = run(&connection, "SELECT a FROM t ORDER BY a").expect("the base query runs");
    assert_eq!(whole.len(), ROWS as usize, "the corpus is not what it says");

    let mut state = 0x1932_7717_u64;
    let mut analysed = false;
    for case in 0..CASES {
        // Half the cases run against the statistics, because they are what
        // make the planner take the other route to the same rows.
        if case == CASES / 2 && !analysed {
            run(&connection, "ANALYZE").expect("ANALYZE runs");
            analysed = true;
        }
        // The corpus moves under the run, so the later cases are asked over a
        // tree that has split and merged rather than one written in order.
        if case > 0 && case % 50 == 0 {
            churn(&connection, case / 50);
        }
        let depth = depth_of(&mut state);
        let condition = predicate(&mut state, depth);
        let mut parts = Vec::new();
        for arm in [
            format!("SELECT a FROM t WHERE {condition}"),
            format!("SELECT a FROM t WHERE NOT ({condition})"),
            format!("SELECT a FROM t WHERE ({condition}) IS NULL"),
        ] {
            match run(&connection, &arm) {
                Ok(rows) => parts.extend(rows),
                // A predicate the binder refuses is not a partition failure -
                // it is a construct this engine does not have - and it is
                // reported rather than skipped silently so that a generator
                // producing mostly refusals cannot look like a passing run.
                Err(failure) => panic!("case {case}: {arm} was refused: {failure}"),
            }
        }
        parts.sort();
        let mut expected = whole.clone();
        expected.sort();
        assert_eq!(
            parts, expected,
            "case {case} (seed {state:#x}, depth {depth}): the three partitions of `{condition}` are \
             not the table"
        );
    }
}

/// The same predicate through an index and through a scan answers the same.
#[test]
fn an_indexed_predicate_answers_what_a_scan_answers() {
    let path = scratch("norec");
    let database = Database::open(&path).expect("the database opens");
    let connection = database.session().expect("the connection opens");
    build(&connection);

    let mut state = 0x1932_9931_u64;
    let mut analysed = false;
    for case in 0..CASES {
        if case == CASES / 2 && !analysed {
            run(&connection, "ANALYZE").expect("ANALYZE runs");
            analysed = true;
        }
        // The corpus moves under the run, so the later cases are asked over a
        // tree that has split and merged rather than one written in order.
        if case > 0 && case % 50 == 0 {
            churn(&connection, case / 50);
        }
        let depth = depth_of(&mut state);
        let condition = predicate(&mut state, depth);
        // The first may be answered through an index; the second has no
        // `WHERE` for the planner to push into one, so it reads every row and
        // applies the predicate in the executor.
        let optimised = format!("SELECT count(*) FROM t WHERE {condition}");
        let scanned = format!("SELECT sum(CASE WHEN ({condition}) THEN 1 ELSE 0 END) FROM t");
        let through_index = run(&connection, &optimised)
            .unwrap_or_else(|failure| panic!("case {case}: {optimised} was refused: {failure}"));
        let through_scan = run(&connection, &scanned)
            .unwrap_or_else(|failure| panic!("case {case}: {scanned} was refused: {failure}"));
        // `sum` over no matching row answers NULL where `count` answers 0, and
        // that difference is SQL's rather than the planner's.
        let scanned_count = match through_scan.first().map(String::as_str) {
            Some("null") => "int:0".to_string(),
            Some(other) => other.to_string(),
            None => String::new(),
        };
        assert_eq!(
            through_index.first().cloned().unwrap_or_default(),
            scanned_count,
            "case {case} (seed {state:#x}, depth {depth}): `{condition}` counts differently through an \
             index and through a scan"
        );
    }
}

/// Returns the one scalar a single-row, single-column query answered.
///
/// @param connection - the database
/// @param sql - the statement
/// @param context - what to say if it did not answer one
fn scalar(connection: &Connection, sql: &str, context: &str) -> String {
    let rows = run(connection, sql).unwrap_or_else(|failure| panic!("{context}: {sql}: {failure}"));
    rows.first().cloned().unwrap_or_default()
}

/// Returns an integer out of a rendered cell, treating NULL as zero.
///
/// `sum` over no rows answers NULL where `count` answers 0, and that difference
/// is SQL's rather than the planner's - so the arms below add partitions up in
/// Rust, where a missing partition is zero.
///
/// @param rendered - one cell as `run` rendered it
fn as_number(rendered: &str) -> i64 {
    match rendered.split_once(':') {
        Some(("int", value)) => value.parse().unwrap_or(0),
        _ => 0,
    }
}

/// An aggregate over the table is the aggregate over its three partitions.
///
/// **Nothing generated an aggregate** (task-2066 §4.4.4). The two arms above
/// grade the planner's route to a *row*; this grades what happens when those
/// rows are added up, which is a different operator over the same access path.
/// A row admitted twice is invisible to a `SELECT a` whose answer is sorted and
/// compared as a set, and it doubles a `sum`.
///
/// `count` and `sum` are exact over the partitions. `min` and `max` are the
/// minimum and maximum of the partitions' own, and `avg` is not - the average
/// of three averages is not the average - so `avg` is checked as
/// `sum / count`, which is what it means.
#[test]
fn an_aggregate_over_the_table_is_the_aggregate_over_its_partitions() {
    let path = scratch("aggregate");
    let database = Database::open(&path).expect("the database opens");
    let connection = database.session().expect("the connection opens");
    build(&connection);

    let whole_count = as_number(&scalar(
        &connection,
        "SELECT count(*) FROM t",
        "the base count",
    ));
    let whole_sum = as_number(&scalar(&connection, "SELECT sum(a) FROM t", "the base sum"));
    assert_eq!(whole_count, ROWS, "the corpus is not what it says");

    let mut state = 0x2068_0001_u64;
    let mut analysed = false;
    for case in 0..CASES {
        if case == CASES / 2 && !analysed {
            run(&connection, "ANALYZE").expect("ANALYZE runs");
            analysed = true;
        }
        if case > 0 && case % 50 == 0 {
            churn(&connection, case / 50);
        }
        let depth = depth_of(&mut state);
        let condition = predicate(&mut state, depth);
        let arms = [
            format!("WHERE {condition}"),
            format!("WHERE NOT ({condition})"),
            format!("WHERE ({condition}) IS NULL"),
        ];

        let mut counted = 0i64;
        let mut summed = 0i64;
        for arm in &arms {
            counted = counted.saturating_add(as_number(&scalar(
                &connection,
                &format!("SELECT count(*) FROM t {arm}"),
                &format!("case {case}"),
            )));
            summed = summed.saturating_add(as_number(&scalar(
                &connection,
                &format!("SELECT sum(a) FROM t {arm}"),
                &format!("case {case}"),
            )));
        }
        assert_eq!(
            counted, whole_count,
            "case {case} (seed {state:#x}, depth {depth}): the partitions of `{condition}` count \
             {counted} rows and the table holds {whole_count}"
        );
        assert_eq!(
            summed, whole_sum,
            "case {case} (seed {state:#x}, depth {depth}): the partitions of `{condition}` sum to \
             {summed} and the table sums to {whole_sum}"
        );

        // `avg` is `sum / count` and is checked as that, because the average of
        // three averages is not the average.
        let partition = &arms[0];
        let part_sum = as_number(&scalar(
            &connection,
            &format!("SELECT sum(a) FROM t {partition}"),
            &format!("case {case}"),
        ));
        let part_count = as_number(&scalar(
            &connection,
            &format!("SELECT count(*) FROM t {partition}"),
            &format!("case {case}"),
        ));
        if part_count > 0 {
            let averaged = as_number(&scalar(
                &connection,
                &format!("SELECT CAST(avg(a) * {part_count} AS INTEGER) FROM t {partition}"),
                &format!("case {case}"),
            ));
            assert!(
                (averaged - part_sum).abs() <= 1,
                "case {case} (seed {state:#x}, depth {depth}): `avg` over `{condition}` is not \
                 its sum over its count: {averaged} against {part_sum}"
            );
        }

        // `min` and `max` over the table are the extremes of the partitions',
        // which is the property a partition that lost a row breaks.
        let extreme = |what: &str| -> i64 {
            arms.iter()
                .map(|arm| {
                    as_number(&scalar(
                        &connection,
                        &format!("SELECT {what}(a) FROM t {arm}"),
                        &format!("case {case}"),
                    ))
                })
                .filter(|value| *value != 0)
                .fold(None::<i64>, |held, value| {
                    Some(match (held, what) {
                        (None, _) => value,
                        (Some(previous), "min") => previous.min(value),
                        (Some(previous), _) => previous.max(value),
                    })
                })
                .unwrap_or(0)
        };
        assert_eq!(
            extreme("min"),
            as_number(&scalar(&connection, "SELECT min(a) FROM t", "the base min")),
            "case {case} (seed {state:#x}, depth {depth}): the partitions of `{condition}` have a \
             different minimum from the table"
        );
        assert_eq!(
            extreme("max"),
            as_number(&scalar(&connection, "SELECT max(a) FROM t", "the base max")),
            "case {case} (seed {state:#x}, depth {depth}): the partitions of `{condition}` have a \
             different maximum from the table"
        );
    }
}

/// `DISTINCT` and `GROUP BY` over the table agree with them over its partitions.
///
/// **Both are collapsing operators, and a collapse is where a duplicate stops
/// being visible** (task-2066 §4.4.4). A row admitted twice by a seek is gone
/// by the time `DISTINCT` has run, so the arm above cannot see it and this one
/// can: the *count* of each group is the sum of its count in the three
/// partitions, and a doubled row makes one group's count too high while the
/// distinct values stay identical.
#[test]
fn distinct_and_grouping_agree_across_the_partitions() {
    let path = scratch("grouping");
    let database = Database::open(&path).expect("the database opens");
    let connection = database.session().expect("the connection opens");
    build(&connection);

    let whole_distinct =
        run(&connection, "SELECT DISTINCT d FROM t ORDER BY d").expect("the base distinct runs");
    let whole_groups = run(
        &connection,
        "SELECT d, count(*) FROM t GROUP BY d ORDER BY d",
    )
    .expect("the base runs");

    let mut state = 0x2068_0002_u64;
    let mut analysed = false;
    for case in 0..CASES {
        if case == CASES / 2 && !analysed {
            run(&connection, "ANALYZE").expect("ANALYZE runs");
            analysed = true;
        }
        if case > 0 && case % 50 == 0 {
            churn(&connection, case / 50);
        }
        let depth = depth_of(&mut state);
        let condition = predicate(&mut state, depth);
        let arms = [
            format!("WHERE {condition}"),
            format!("WHERE NOT ({condition})"),
            format!("WHERE ({condition}) IS NULL"),
        ];

        // The distinct values of the three partitions together are the table's.
        let mut seen: Vec<String> = Vec::new();
        for arm in &arms {
            let rows = run(&connection, &format!("SELECT DISTINCT d FROM t {arm}"))
                .unwrap_or_else(|failure| panic!("case {case}: {arm}: {failure}"));
            seen.extend(rows);
        }
        seen.sort();
        seen.dedup();
        let mut wanted = whole_distinct.clone();
        wanted.sort();
        wanted.dedup();
        assert_eq!(
            seen, wanted,
            "case {case} (seed {state:#x}, depth {depth}): the distinct values under \
             `{condition}` are not the table's"
        );

        // And each group's count is the sum of its count in each partition.
        let mut totals: std::collections::BTreeMap<String, i64> = std::collections::BTreeMap::new();
        for arm in &arms {
            let rows = run(
                &connection,
                &format!("SELECT d, count(*) FROM t {arm} GROUP BY d"),
            )
            .unwrap_or_else(|failure| panic!("case {case}: {arm}: {failure}"));
            for row in rows {
                let Some((key, count)) = row.split_once('|') else {
                    continue;
                };
                *totals.entry(key.to_string()).or_insert(0) += as_number(count);
            }
        }
        let combined: Vec<String> = totals
            .iter()
            .map(|(key, count)| format!("{key}|int:{count}"))
            .collect();
        let mut expected = whole_groups.clone();
        expected.sort();
        let mut found = combined;
        found.sort();
        assert_eq!(
            found, expected,
            "case {case} (seed {state:#x}, depth {depth}): the group counts under `{condition}` \
             do not add up to the table's"
        );
    }
}

/// A join answers the same rows whichever partition the predicate is on.
///
/// **The index is built before the rows are loaded, on purpose** (task-2066
/// §4.4.4). That is the order an application writes - `CREATE TABLE`,
/// `CREATE INDEX`, then the data - and it is the order the read gate has never
/// measured: every published figure is taken on a tree imported from SQLite,
/// which is packed, so no figure has touched a leaf holding delta rows. §4.3.4
/// is about what that costs, and this is the arm that says the answers are
/// right while it is changed. A delta row shadows a sorted row, and a wrong
/// merge returns a duplicate or a stale row - which is exactly what a partition
/// check sees.
#[test]
fn a_join_partitions_the_same_way_a_scan_does() {
    let path = scratch("join");
    let database = Database::open(&path).expect("the database opens");
    let connection = database.session().expect("the connection opens");
    build(&connection);

    for statement in [
        "CREATE TABLE u(g INTEGER, label TEXT)",
        // Before the load. The whole point of the arm.
        "CREATE INDEX u_g ON u(g)",
        "BEGIN",
    ] {
        run(&connection, statement).unwrap_or_else(|failure| panic!("{statement}: {failure}"));
    }
    for row in 0..53i64 {
        let sql = format!("INSERT INTO u VALUES ({row}, 'g{row}')");
        run(&connection, &sql).unwrap_or_else(|failure| panic!("{sql}: {failure}"));
    }
    run(&connection, "COMMIT").expect("the join table commits");

    let joined = "FROM t JOIN u ON u.g = t.d";
    let whole = run(
        &connection,
        "SELECT t.a FROM t JOIN u ON u.g = t.d ORDER BY t.a",
    )
    .expect("the base join runs");
    assert!(
        !whole.is_empty(),
        "the join matches nothing, so this arm grades nothing"
    );

    let mut state = 0x2068_0003_u64;
    let mut analysed = false;
    for case in 0..CASES {
        if case == CASES / 2 && !analysed {
            run(&connection, "ANALYZE").expect("ANALYZE runs");
            analysed = true;
        }
        if case > 0 && case % 50 == 0 {
            churn(&connection, case / 50);
        }
        let depth = depth_of(&mut state);
        let condition = predicate(&mut state, depth);
        let mut parts = Vec::new();
        for arm in [
            format!("SELECT t.a {joined} WHERE {condition}"),
            format!("SELECT t.a {joined} WHERE NOT ({condition})"),
            format!("SELECT t.a {joined} WHERE ({condition}) IS NULL"),
        ] {
            let rows = run(&connection, &arm)
                .unwrap_or_else(|failure| panic!("case {case}: {arm} was refused: {failure}"));
            parts.extend(rows);
        }
        parts.sort();
        let mut expected = whole.clone();
        expected.sort();
        assert_eq!(
            parts, expected,
            "case {case} (seed {state:#x}, depth {depth}): the three partitions of `{condition}` \
             over a join are not the join"
        );
    }
}

/// A recursive walk's deepest node is the one an ordered, limited query answers.
///
/// **The arm for §4.1.1.** `ORDER BY depth DESC LIMIT k` over a recursive CTE
/// applied the limit to the *generation* and then sorted what it had kept, so
/// the hierarchy walk for the deepest node answered the root. The generated
/// form is here rather than only the four fixed statements in
/// `corpora/differential-part8/cte.cases`, because the defect's shape is "the
/// limit and the sort are in the wrong order" and that is a property of every
/// depth and every width, not of the five-row chain that first showed it.
///
/// Graded against the same answer computed without a `LIMIT`, which needs no
/// oracle: the first `k` rows of the fully sorted result are what a `LIMIT k`
/// over the sort has to be.
#[test]
fn a_limited_recursive_walk_answers_the_deepest_nodes() {
    let path = scratch("recursive");
    let database = Database::open(&path).expect("the database opens");
    let connection = database.session().expect("the connection opens");

    let mut state = 0x2068_0004_u64;
    for case in 0..40usize {
        let table = format!("node{case}");
        run(
            &connection,
            &format!("CREATE TABLE {table}(id INTEGER PRIMARY KEY, parent INTEGER)"),
        )
        .expect("the hierarchy table is made");
        // A chain of a generated length, with a generated number of leaves
        // hanging off each level - so the walk is neither always a line nor
        // always a star.
        let deep = below(&mut state, 12) + 2;
        let wide = below(&mut state, 3) + 1;
        run(&connection, "BEGIN").expect("the load begins");
        run(
            &connection,
            &format!("INSERT INTO {table} VALUES (1, NULL)"),
        )
        .expect("the root is made");
        let mut next_id = 2i64;
        let mut parent = 1i64;
        for _ in 0..deep {
            let level_head = next_id;
            for _ in 0..wide {
                let sql = format!("INSERT INTO {table} VALUES ({next_id}, {parent})");
                run(&connection, &sql).unwrap_or_else(|failure| panic!("{sql}: {failure}"));
                next_id += 1;
            }
            parent = level_head;
        }
        run(&connection, "COMMIT").expect("the load commits");

        let walk = format!(
            "WITH RECURSIVE w(id, depth) AS (SELECT id, 0 FROM {table} WHERE parent IS NULL \
             UNION ALL SELECT n.id, w.depth + 1 FROM {table} n JOIN w ON n.parent = w.id) \
             SELECT id, depth FROM w ORDER BY depth DESC, id ASC"
        );
        let sorted = run(&connection, &walk)
            .unwrap_or_else(|failure| panic!("case {case}: {walk} was refused: {failure}"));
        assert!(!sorted.is_empty(), "case {case}: the walk produced no rows");
        for take in [1usize, 2, 3] {
            let limited = run(&connection, &format!("{walk} LIMIT {take}"))
                .unwrap_or_else(|failure| panic!("case {case}: the limited walk: {failure}"));
            let wanted: Vec<String> = sorted.iter().take(take).cloned().collect();
            assert_eq!(
                limited, wanted,
                "case {case} (deep {deep}, wide {wide}): `LIMIT {take}` over the walk answered \
                 {limited:?} where the first {take} of the sorted walk are {wanted:?}. That is \
                 the limit being applied to the generation rather than to the sort."
            );
        }
    }
}
