[package]
name = "rustdb-vm"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Bytecode representation, compiler, verifier, virtual machine, cursors, and relational operators."

[dependencies]
rustdb-base = { workspace = true }
rustdb-value = { workspace = true }
rustdb-sql = { workspace = true }
rustdb-catalog = { workspace = true }
rustdb-storage = { workspace = true }
rustdb-ext = { workspace = true }
