-- Nikaya's own statements, so a consumer's corpus is something the suite runs.
--
-- Built by `tools/extract-nikaya-workload.py` from `C:/jason/dev/nikaya/server`:
-- every SQL statement literal in `src/`, de-duplicated, with the file and line
-- it came from, and the schema its migrations build.
--
-- ## Why the statements and not the data
--
-- Because the escape that prompted this was a *refusal*. A compound `SELECT`
-- used as a derived table was declined by the binder, and a document view
-- answered HTTP 500 - and no amount of the right data would have found it,
-- because the statement never compiled. What was missing was the statement.
--
-- Nikaya's data is private mail and none of it is here. `story_workload_replay.rs`
-- builds rows against this schema with values it chooses, and the `-- params:`
-- line under each statement is one value per placeholder, taken from the column
-- the placeholder stands for, so a predicate matches a row rather than nothing.
-- A `-- inferred:` line under a statement names the placeholders that stand
-- beside no column this schema declares; those are bound as text.
--
-- ## The format
--
-- Two sections, each opened by a line that is nothing but its marker. The
-- schema section is the migrations, concatenated, and is what the replay builds
-- before it runs anything. The statements section is one block per statement: a
-- statement line naming its source, a params line holding a JSON array, and the
-- SQL, ending in a semicolon.
--
-- A statement the engine refuses is a failure unless its source is named in
-- `allow.list` beside this file with a ticket key - the same arrangement
-- `differential_part8.rs` has, and for the same reason: a list that only grows
-- is a list of things nobody will take off it, so an allow listed statement
-- that starts working fails too.
--
-- ## What is not here
--
-- 159 statements are carried. 17 literals are not, because they are `format!`
-- templates rather than statements: Nikaya interpolates a column list, a table
-- name or a key into them, and what reaches the engine is whatever the
-- interpolation produced. Running the literal would assert that the engine
-- refuses a brace. They are:
--
--   repositories/corpus.rs:102
--   repositories/corpus.rs:164
--   repositories/corpus.rs:335
--   services/adopt.rs:213
--   services/adopt.rs:224
--   services/adopt.rs:284
--   services/adopt.rs:286
--   services/adopt.rs:822
--   services/verify.rs:166
--   services/verify.rs:221
--   services/verify.rs:269
--   services/verify.rs:305
--   services/verify.rs:407
--   services/verify.rs:463
--   services/verify.rs:500
--   services/verify.rs:546
--   services/verify.rs:589
--
-- ## Regenerating
--
--     python tools/extract-nikaya-workload.py
--
-- When Nikaya adds a statement this file goes stale, and
-- `workload_freshness::the_workload_matches_the_consumers_source` says so on a
-- machine that has the Nikaya checkout and prints `; skipping` on one that does
-- not.

-- section: schema

-- from src/db.rs, which creates the migration ledger before it can read it
CREATE TABLE IF NOT EXISTS schema_migration (
  name       TEXT PRIMARY KEY,
  applied_at INTEGER NOT NULL
);

-- from migrations/inillucent/001_init.sql
-- Nikaya's schema on inillucent: the whole record, in one file, with no other database.
--
-- This is the PostgreSQL schema of migrations/001_init.sql through 004_auth.sql carried over to the
-- engine's SQLite dialect. Four kinds of column changed and the reason for each is on the column:
--
--   UUID          -> TEXT, the canonical hyphenated form, generated by the server
--   TIMESTAMPTZ   -> INTEGER, microseconds since the Unix epoch, UTC
--   JSONB         -> TEXT holding the JSON
--   TEXT[]        -> TEXT holding a JSON array
--   halfvec(768)  -> VECTOR(768), 768 little endian f32
--
-- Two PostgreSQL columns are not carried at all. `chunk.search_vector` was the lexical index for
-- PostgreSQL full text search, and the lexical branch has been BM25 inside the retrieval engine
-- since task-1774. The GIN and trigram indexes went with it: substring filters on a sender or a
-- participant are resolved against the retrieval index's dictionary, not with a SQL LIKE.

-- One connected corpus source. Gmail is the first; the shape is deliberately source agnostic.
CREATE TABLE source_account (
  id                  TEXT PRIMARY KEY,
  source_type         TEXT NOT NULL,
  provider_account    TEXT NOT NULL,
  display_name        TEXT,
  authorization_state TEXT NOT NULL DEFAULT 'authorized',
  created_at          INTEGER NOT NULL,
  updated_at          INTEGER NOT NULL,
  UNIQUE (source_type, provider_account)
);

-- Gmail's resumable sync checkpoint. One row per account.
CREATE TABLE gmail_sync_state (
  source_account_id      TEXT PRIMARY KEY REFERENCES source_account(id) ON DELETE CASCADE,
  last_history_id        INTEGER,
  full_sync_page_token   TEXT,
  full_sync_started_at   INTEGER,
  full_sync_completed_at INTEGER,
  last_incremental_at    INTEGER,
  messages_total_remote  INTEGER,
  updated_at             INTEGER NOT NULL
);

-- A retrievable unit of source content: an email message, or one attachment's extracted text.
CREATE TABLE document (
  id                TEXT PRIMARY KEY,
  source_account_id TEXT NOT NULL REFERENCES source_account(id) ON DELETE CASCADE,
  kind              TEXT NOT NULL CHECK (kind IN ('email', 'attachment')),
  provider_id       TEXT NOT NULL,
  title             TEXT NOT NULL DEFAULT '',
  body_text         TEXT NOT NULL DEFAULT '',
  search_body       TEXT NOT NULL DEFAULT '',
  raw_source        TEXT,
  content_hash      TEXT NOT NULL,
  source_timestamp  INTEGER,
  deleted_at        INTEGER,
  indexed_at        INTEGER,
  created_at        INTEGER NOT NULL,
  updated_at        INTEGER NOT NULL,
  UNIQUE (source_account_id, kind, provider_id)
);
CREATE INDEX document_source_timestamp_idx ON document (source_timestamp DESC);
CREATE INDEX document_kind_idx ON document (kind);
-- The queue the ingestion pass drains. Partial, so it stays the size of the backlog rather than the
-- size of the corpus: 66,776 documents are indexed and the index holds the handful that are not.
CREATE INDEX document_pending_index_idx ON document (indexed_at)
  WHERE indexed_at IS NULL AND deleted_at IS NULL;

-- Email specific metadata for documents of kind 'email'.
CREATE TABLE email_message (
  document_id     TEXT PRIMARY KEY REFERENCES document(id) ON DELETE CASCADE,
  gmail_thread_id TEXT NOT NULL,
  rfc_message_id  TEXT,
  subject         TEXT NOT NULL DEFAULT '',
  from_name       TEXT,
  from_address    TEXT,
  sent_at         INTEGER,
  labels          TEXT NOT NULL DEFAULT '[]',
  snippet         TEXT NOT NULL DEFAULT '',
  history_id      INTEGER,
  size_estimate   INTEGER,
  has_attachment  INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX email_message_thread_idx ON email_message (gmail_thread_id);
CREATE INDEX email_message_from_idx ON email_message (from_address);
CREATE INDEX email_message_sent_idx ON email_message (sent_at DESC);

-- Every from/to/cc/bcc participant, normalized so sender and recipient filters are indexable.
CREATE TABLE email_participant (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  document_id  TEXT NOT NULL REFERENCES document(id) ON DELETE CASCADE,
  kind         TEXT NOT NULL CHECK (kind IN ('from', 'to', 'cc', 'bcc', 'reply-to')),
  display_name TEXT,
  address      TEXT NOT NULL,
  ordinal      INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX email_participant_document_idx ON email_participant (document_id);
CREATE INDEX email_participant_address_idx ON email_participant (address, kind);

-- Content addressed attachment bytes. Identical bytes are stored once and linked many times.
CREATE TABLE attachment (
  id                  TEXT PRIMARY KEY,
  sha256              TEXT NOT NULL UNIQUE,
  object_path         TEXT NOT NULL,
  byte_size           INTEGER NOT NULL,
  mime_type           TEXT NOT NULL DEFAULT 'application/octet-stream',
  safe_filename       TEXT NOT NULL,
  extraction_status   TEXT NOT NULL DEFAULT 'pending'
    CHECK (extraction_status IN ('pending', 'extracted', 'unsupported', 'failed', 'skipped')),
  extracted_text      TEXT,
  extractor_version   TEXT,
  error_summary       TEXT,
  created_at          INTEGER NOT NULL,
  updated_at          INTEGER NOT NULL,
  extraction_metadata TEXT
);
CREATE INDEX attachment_status_idx ON attachment (extraction_status);
CREATE INDEX attachment_mime_idx ON attachment (mime_type);

-- Links an attachment's bytes to the message it arrived in.
CREATE TABLE message_attachment (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  document_id         TEXT NOT NULL REFERENCES document(id) ON DELETE CASCADE,
  attachment_id       TEXT NOT NULL REFERENCES attachment(id) ON DELETE CASCADE,
  gmail_part_id       TEXT,
  gmail_attachment_id TEXT,
  content_id          TEXT,
  original_filename   TEXT NOT NULL DEFAULT '',
  is_inline           INTEGER NOT NULL DEFAULT 0,
  ordinal             INTEGER NOT NULL DEFAULT 0,
  UNIQUE (document_id, attachment_id, ordinal)
);
CREATE INDEX message_attachment_document_idx ON message_attachment (document_id);
CREATE INDEX message_attachment_attachment_idx ON message_attachment (attachment_id);

-- Attachment bytes that still need downloading, kept durable so a crash resumes rather than restarts.
CREATE TABLE attachment_download_queue (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  document_id         TEXT NOT NULL REFERENCES document(id) ON DELETE CASCADE,
  gmail_message_id    TEXT NOT NULL,
  gmail_part_id       TEXT,
  gmail_attachment_id TEXT NOT NULL,
  original_filename   TEXT NOT NULL DEFAULT '',
  mime_type           TEXT NOT NULL DEFAULT 'application/octet-stream',
  content_id          TEXT,
  is_inline           INTEGER NOT NULL DEFAULT 0,
  declared_size       INTEGER,
  ordinal             INTEGER NOT NULL DEFAULT 0,
  status              TEXT NOT NULL DEFAULT 'queued'
    CHECK (status IN ('queued', 'done', 'failed')),
  attempts            INTEGER NOT NULL DEFAULT 0,
  error_summary       TEXT,
  created_at          INTEGER NOT NULL,
  UNIQUE (document_id, gmail_attachment_id, ordinal)
);
CREATE INDEX attachment_download_queue_pending_idx ON attachment_download_queue (status)
  WHERE status = 'queued';

-- One embeddable slice of a document.
CREATE TABLE chunk (
  id                 TEXT PRIMARY KEY,
  document_id        TEXT NOT NULL REFERENCES document(id) ON DELETE CASCADE,
  ordinal            INTEGER NOT NULL,
  content            TEXT NOT NULL,
  heading            TEXT NOT NULL DEFAULT '',
  locator            TEXT,
  char_count         INTEGER NOT NULL,
  content_hash       TEXT NOT NULL,
  chunker_version    TEXT NOT NULL,
  created_at         INTEGER NOT NULL,
  embedding_attempts INTEGER NOT NULL DEFAULT 0,
  embedding_error    TEXT,
  UNIQUE (document_id, ordinal)
);
CREATE INDEX chunk_document_idx ON chunk (document_id);
CREATE INDEX chunk_embedding_attempts_idx ON chunk (embedding_attempts)
  WHERE embedding_attempts > 0;

-- Vectors are versioned by model so two embedding spaces are never mixed in one index.
--
-- The column is declared VECTOR(768) rather than BLOB so a value that is not 768 floats wide is
-- refused when it is written. A wrong width is otherwise found when the retrieval index is built,
-- which is minutes later and a long way from the code that produced it.
--
-- There is deliberately no `USING inillucent_hnsw` index over this column. That index is the same
-- HNSW the retrieval engine runs, so building one here would be a second graph over the same
-- 601,862 vectors, maintained on every write, to answer a query nothing asks: retrieval goes through
-- `services/retrieval.rs`. Leaving it unindexed also means `ORDER BY vector_distance_cos(...)` here
-- is an exhaustive scan and therefore exact, which gives the recall gate an oracle in the same file.
CREATE TABLE chunk_embedding (
  chunk_id        TEXT NOT NULL REFERENCES chunk(id) ON DELETE CASCADE,
  embedding_model TEXT NOT NULL,
  dimension       INTEGER NOT NULL,
  embedding       VECTOR(768) NOT NULL,
  indexed_at      INTEGER NOT NULL,
  PRIMARY KEY (chunk_id, embedding_model)
);

-- Durable background work: sync passes, extraction, and embedding batches.
CREATE TABLE sync_job (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  source_account_id TEXT REFERENCES source_account(id) ON DELETE CASCADE,
  job_type          TEXT NOT NULL,
  status            TEXT NOT NULL DEFAULT 'queued'
    CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
  counters          TEXT NOT NULL DEFAULT '{}',
  checkpoint        TEXT,
  attempts          INTEGER NOT NULL DEFAULT 0,
  error_summary     TEXT,
  started_at        INTEGER,
  finished_at       INTEGER,
  created_at        INTEGER NOT NULL,
  updated_at        INTEGER NOT NULL
);
CREATE INDEX sync_job_status_idx ON sync_job (status, created_at DESC);

-- A retrieval side projection of the metadata every filter needs, for email and attachment
-- documents alike. An attachment document inherits its parent message's sender, labels and thread so
-- one sender filter matches both the email and the PDF that arrived on it.
CREATE TABLE document_meta (
  document_id    TEXT PRIMARY KEY REFERENCES document(id) ON DELETE CASCADE,
  kind           TEXT NOT NULL,
  from_address   TEXT,
  from_name      TEXT,
  labels         TEXT NOT NULL DEFAULT '[]',
  thread_id      TEXT,
  has_attachment INTEGER NOT NULL DEFAULT 0,
  sent_at        INTEGER
);
CREATE INDEX document_meta_from_idx ON document_meta (from_address);
CREATE INDEX document_meta_thread_idx ON document_meta (thread_id);
CREATE INDEX document_meta_sent_idx ON document_meta (sent_at DESC);
CREATE INDEX document_meta_kind_idx ON document_meta (kind);

-- One person who may sign in. Two exist: the mailbox owner and the estate executor.
CREATE TABLE app_user (
  username      TEXT PRIMARY KEY,
  display_name  TEXT NOT NULL,
  role          TEXT NOT NULL CHECK (role IN ('owner', 'executor')),
  password_hash TEXT NOT NULL,
  created_at    INTEGER NOT NULL,
  updated_at    INTEGER NOT NULL
);

-- One live browser session. Only the SHA-256 of the cookie value is stored, so a database read
-- cannot be replayed as a login the way a stored bearer token could.
CREATE TABLE app_session (
  token_sha256 TEXT PRIMARY KEY,
  username     TEXT NOT NULL REFERENCES app_user(username) ON DELETE CASCADE,
  created_at   INTEGER NOT NULL,
  last_seen_at INTEGER NOT NULL,
  expires_at   INTEGER NOT NULL
);
CREATE INDEX app_session_username_idx ON app_session (username);
CREATE INDEX app_session_expires_idx ON app_session (expires_at);

-- Which person owns one Claude Code conversation id. The browser picks the id, so without this a
-- second user could resume somebody else's conversation just by replaying it.
CREATE TABLE agent_session (
  session_id   TEXT PRIMARY KEY,
  username     TEXT NOT NULL REFERENCES app_user(username) ON DELETE CASCADE,
  created_at   INTEGER NOT NULL,
  last_used_at INTEGER NOT NULL
);
CREATE INDEX agent_session_username_idx ON agent_session (username);

-- from migrations/inillucent/002_queue_indexes.sql
-- Plain indexes for the two work queues, because a partial index is never chosen.
--
-- `001_init.sql` carries the two partial indexes PostgreSQL had:
--
--   CREATE INDEX document_pending_index_idx ON document (indexed_at)
--     WHERE indexed_at IS NULL AND deleted_at IS NULL;
--   CREATE INDEX attachment_download_queue_pending_idx ON attachment_download_queue (status)
--     WHERE status = 'queued';
--
-- Both are accepted and stored, and neither is ever selected - not even for a query whose predicate
-- is character for character the index's own `WHERE` clause. Reproduced on three rows: a table with a
-- partial index on `(done) WHERE done IS NULL AND gone IS NULL` plans `SELECT id FROM t WHERE done IS
-- NULL AND gone IS NULL` as a full `SCAN`, and adding a plain index on the same column turns it into
-- a covering index scan. Filed as part of task-1880.
--
-- The cost here was not small. `document` is 66,776 rows whose leaves carry the message body and the
-- raw provider payload, so the scan the ingestion pass runs to find its own backlog read gigabytes of
-- text to answer a question that normally has no rows at all: measured at **1,280 ms**, on a queue
-- that is usually empty.
--
-- These are the plain indexes the planner does use. The partial ones are left in place: they cost
-- little, they are correct, and they are what should be selected once the planner can.

CREATE INDEX IF NOT EXISTS document_indexed_at_idx ON document (indexed_at);
CREATE INDEX IF NOT EXISTS attachment_download_queue_status_idx ON attachment_download_queue (status);

-- from migrations/inillucent/003_embedded_flag.sql
-- A flag on the chunk, because a LEFT JOIN is a nested loop with the inner side scanned.
--
-- "Which chunks have no vector yet" was an anti join: `chunk LEFT JOIN chunk_embedding ON
-- e.chunk_id = c.id AND e.embedding_model = ? WHERE e.chunk_id IS NULL`. PostgreSQL answered it with
-- a hash anti join in milliseconds. Here the plan is
--
--   SCAN c USING COVERING INDEX sqlite_autoindex_chunk_1
--   SCAN e
--
-- - the outer side scanned, and the inner side scanned again for every one of its rows. On this
-- corpus that is 601,862 x 601,862, and it does not finish: a sync sat on one core for nine minutes
-- with no disk and no network before it was stopped, and it had not left the first phase.
--
-- The same join written as `NOT EXISTS` is no better, and an INNER JOIN on the identical key **is**
-- planned as an index seek, so this is specific to the outer join rather than to the key. Filed as
-- part of task-1880.
--
-- So the question stops being a join. `chunk.embedded_at` records when a chunk's vector was written,
-- `store_embeddings` sets it in the same transaction as the vector, and the queue query becomes a
-- seek on an index. The two counts stay derivable from `chunk_embedding`, so nothing here is the only
-- copy of anything: this column is a cache of a fact the other table already holds, and the
-- reconciliation that repairs the retrieval index would show it up if it ever drifted.

ALTER TABLE chunk ADD COLUMN embedded_at INTEGER;

CREATE INDEX IF NOT EXISTS chunk_embedded_at_idx ON chunk (embedded_at);

-- `embedding_attempts >= 3` is the poison chunk check, and `001_init.sql` indexes it partially -
-- `WHERE embedding_attempts > 0` - which is never selected. A plain index is.
CREATE INDEX IF NOT EXISTS chunk_embedding_attempts_plain_idx ON chunk (embedding_attempts);

-- from migrations/inillucent/004_embedding_queue.sql
-- The embedding backlog as a table, because neither of the other two ways works here.
--
-- The question is "which chunks have no vector yet", asked once per ingestion page and once per
-- status render. Three ways to answer it, and the first two are closed:
--
-- 1. **Anti join** - `chunk LEFT JOIN chunk_embedding ... WHERE e.chunk_id IS NULL`, which is what
--    PostgreSQL answered with a hash anti join in milliseconds. Here a LEFT JOIN is a nested loop
--    with the inner side scanned: `SCAN c` then `SCAN e`, which on 601,862 rows is 601,862 squared
--    and does not finish. `NOT EXISTS` is planned no better. An INNER JOIN on the identical key *is*
--    an index seek, so this is specific to the outer join.
--
-- 2. **A flag on the chunk** - `003_embedded_flag.sql` added `chunk.embedded_at` for exactly this.
--    Filling it is the problem. Per row, it is 601,862 seeks and rewrites of a row over a kilobyte
--    wide, measured at 1 MB/s and about an hour; and the run that was killed part way through left a
--    database whose redo log could not be replayed. Set based, in one statement, it fails outright:
--
--        Error: the mini-columns do not fit in one page
--
--    A column added by ALTER TABLE and then filled on every row makes some leaf need a layout it
--    cannot have. So the column is there, empty, and unused; it is left rather than dropped because
--    dropping it is another rewrite of every row. Both failures are on task-1880.
--
-- 3. **A queue**, which is this. A chunk is put here when it is written and taken out when its
--    vector is stored, both inside the transaction that does the other half, so the two can never
--    disagree. In the steady state it holds nothing, so the question costs nothing to ask.
--
-- It starts empty, and empty is the correct starting state: every one of the 601,862 chunks in this
-- corpus has a vector, which is checked rather than assumed - `chunk` and `chunk_embedding` both
-- count 601,862. A chunk that somehow has neither a vector nor a queue row would be invisible to the
-- embedding pass, so `nikaya-server reconcile-embedding-queue` re-derives the queue from the two
-- tables and is what a suspicion gets answered with.

CREATE TABLE IF NOT EXISTS embedding_queue (
  chunk_id  TEXT PRIMARY KEY REFERENCES chunk(id) ON DELETE CASCADE,
  queued_at INTEGER NOT NULL
);

-- section: statements

-- statement: db.rs:677
-- params: []
CREATE TABLE IF NOT EXISTS schema_migration (
    name       TEXT PRIMARY KEY,
    applied_at INTEGER NOT NULL
);

-- statement: db.rs:688
-- params: ["row-0001"]
SELECT name FROM schema_migration WHERE name = ?1;

-- statement: db.rs:702
-- params: ["row-0001", 1]
INSERT INTO schema_migration (name, applied_at) VALUES (?1, ?2);

-- statement: db.rs:743
-- params: ["row-0001"]
SELECT id FROM chunk WHERE id > ?1 AND embedding_attempts < 3
ORDER BY id LIMIT 5000;

-- statement: db.rs:762
-- params: ["row-0001", "row-0001"]
SELECT chunk_id FROM chunk_embedding
WHERE chunk_id = ?1 AND embedding_model = ?2;

-- statement: db.rs:771
-- params: ["row-0001", 1]
INSERT INTO embedding_queue (chunk_id, queued_at) VALUES (?1, ?2)
ON CONFLICT (chunk_id) DO NOTHING;

-- statement: main.rs:284
-- params: []
SELECT count(*) AS total FROM document;

-- statement: repositories/accounts.rs:33
-- params: ["row-0001"]
SELECT id FROM source_account WHERE source_type = 'gmail' AND provider_account = ?1;

-- statement: repositories/accounts.rs:40
-- params: ["row-0001", "row-0001", 1]
UPDATE source_account
  SET display_name = ?2, authorization_state = 'authorized', updated_at = ?3
WHERE id = ?1;

-- statement: repositories/accounts.rs:50
-- params: ["row-0001", "row-0001", 1]
INSERT INTO source_account
   (id, source_type, provider_account, display_name, authorization_state, created_at, updated_at)
VALUES (?1, 'gmail', ?2, ?2, 'authorized', ?3, ?3);

-- statement: repositories/accounts.rs:60
-- params: ["row-0001"]
SELECT source_account_id FROM gmail_sync_state WHERE source_account_id = ?1;

-- statement: repositories/accounts.rs:66
-- params: ["row-0001", 1]
INSERT INTO gmail_sync_state (source_account_id, updated_at) VALUES (?1, ?2);

-- statement: repositories/accounts.rs:81
-- params: []
SELECT id FROM source_account WHERE source_type = 'gmail' ORDER BY created_at LIMIT 1;

-- statement: repositories/accounts.rs:95
-- params: ["row-0001"]
SELECT source_account_id, last_history_id, full_sync_page_token, full_sync_started_at,
       full_sync_completed_at, last_incremental_at, messages_total_remote
FROM gmail_sync_state WHERE source_account_id = ?1;

-- statement: repositories/accounts.rs:122
-- params: ["row-0001", "row-0001", 1]
UPDATE gmail_sync_state SET full_sync_page_token = ?2, updated_at = ?3
WHERE source_account_id = ?1;

-- statement: repositories/accounts.rs:138
-- params: ["row-0001", 1, 1, 1]
UPDATE gmail_sync_state
SET full_sync_started_at = COALESCE(full_sync_started_at, ?4),
    full_sync_completed_at = NULL,
    last_history_id = COALESCE(last_history_id, ?2),
    messages_total_remote = ?3,
    updated_at = ?4
WHERE source_account_id = ?1;

-- statement: repositories/accounts.rs:158
-- params: ["row-0001", 1, 1]
UPDATE gmail_sync_state
SET full_sync_completed_at = ?3, full_sync_page_token = NULL,
    last_history_id = ?2, updated_at = ?3
WHERE source_account_id = ?1;

-- statement: repositories/accounts.rs:175
-- params: ["row-0001", 1, 1]
UPDATE gmail_sync_state
SET last_history_id = ?2, last_incremental_at = ?3, updated_at = ?3
WHERE source_account_id = ?1;

-- statement: repositories/accounts.rs:190
-- params: ["row-0001", 1]
UPDATE gmail_sync_state
SET last_history_id = NULL, full_sync_completed_at = NULL, updated_at = ?2
WHERE source_account_id = ?1;

-- statement: repositories/attachments.rs:53
-- params: ["row-0001", 25]
SELECT id, safe_filename, extractor_version,
       extraction_metadata ->> '$.method' AS method, extracted_text
FROM attachment
WHERE extracted_text IS NOT NULL AND id > ?1
ORDER BY id LIMIT ?2;

-- statement: repositories/attachments.rs:94
-- params: ["row-0001", 1]
UPDATE attachment
SET extraction_status = 'pending', error_summary = NULL, extraction_metadata = NULL,
    extractor_version = NULL, updated_at = ?2
WHERE id = ?1;

-- statement: repositories/attachments.rs:114
-- params: [1]
UPDATE attachment
SET extraction_status = 'pending', error_summary = NULL, extraction_metadata = NULL,
    extractor_version = NULL, updated_at = ?1
WHERE extracted_text IS NOT NULL OR extraction_status IN ('failed', 'pending');

-- statement: repositories/attachments.rs:131
-- params: ["row-0001", 1]
UPDATE attachment
SET extraction_status = 'pending', error_summary = NULL, extraction_metadata = NULL,
    extractor_version = NULL, updated_at = ?2
WHERE (extracted_text IS NOT NULL OR extraction_status = 'failed')
  AND (extractor_version IS NULL OR extractor_version <> ?1);

-- statement: repositories/attachments.rs:205
-- params: []
SELECT a.id AS id, a.safe_filename AS safe_filename, a.mime_type AS mime_type,
       a.byte_size AS byte_size, a.extraction_status AS extraction_status,
       a.extracted_text AS extracted_text, a.extractor_version AS extractor_version,
       a.extraction_metadata ->> '$.textExtractor' AS text_extractor,
       a.extraction_metadata ->> '$.primaryFailed' AS primary_failed,
       (SELECT count(*) FROM message_attachment ma
         WHERE ma.attachment_id = a.id AND ma.is_inline = 0) AS attached_count
FROM attachment a;

-- statement: repositories/attachments.rs:258
-- params: ["row-0001", 1]
UPDATE attachment
SET extraction_status = 'pending', error_summary = NULL,
    extraction_metadata = NULL, updated_at = ?2
WHERE id = ?1;

-- statement: repositories/attachments.rs:275
-- params: ["row-0001", 1]
UPDATE attachment SET extraction_status = 'unsupported',
    error_summary = 'OCR completed but found no searchable text', updated_at = ?2
WHERE extractor_version = ?1 AND extraction_status = 'failed'
  AND error_summary = 'OCR produced no text; primary=; fallback=';

-- statement: repositories/attachments.rs:283
-- params: ["row-0001", 1]
UPDATE attachment SET extraction_status = 'unsupported',
    error_summary = 'the image attachment was unreadable or mislabeled', updated_at = ?2
WHERE extractor_version = ?1 AND extraction_status = 'failed'
  AND error_summary = 'image decoder could not open the attachment';

-- statement: repositories/attachments.rs:299
-- params: []
SELECT COALESCE(extraction_metadata ->> '$.coverage', 'unreported') AS coverage,
       count(*) AS total
FROM attachment WHERE extraction_metadata ->> '$.method' = 'paddleocr-vl-1.6'
GROUP BY 1 ORDER BY 1;

-- statement: repositories/attachments.rs:388
-- params: []
SELECT id, provider_id FROM document WHERE kind = 'attachment' AND deleted_at IS NULL;

-- statement: repositories/attachments.rs:404
-- params: ["row-0001"]
SELECT COALESCE(extraction_metadata ->> '$.method', 'preexisting') AS method,
       extracted_text
FROM attachment WHERE id = ?1 AND extracted_text IS NOT NULL;

-- statement: repositories/attachments.rs:419
-- params: ["row-0001"]
SELECT 1 AS found FROM message_attachment ma
JOIN email_message e ON e.document_id = ma.document_id
WHERE ma.attachment_id = ?1
  AND (lower(e.from_name) LIKE '%terri shaw%' OR lower(e.from_address) LIKE '%terrishaw%')
LIMIT 1;

-- statement: repositories/attachments.rs:440
-- params: ["row-0001"]
SELECT concat_ws(':', extraction_metadata ->> '$.method',
                      extraction_metadata ->> '$.textExtractor') AS method,
       count(*) AS total
FROM attachment WHERE extractor_version = ?1 AND extraction_metadata IS NOT NULL
GROUP BY 1 ORDER BY 1;

-- statement: repositories/attachments.rs:455
-- params: ["row-0001"]
SELECT COALESCE(error_summary, 'unknown') AS summary, count(*) AS total FROM attachment
WHERE extractor_version = ?1 AND extraction_status = 'failed'
GROUP BY 1 ORDER BY 2 DESC LIMIT 20;

-- statement: repositories/attachments.rs:468
-- params: ["row-0001"]
SELECT safe_filename, object_path, COALESCE(error_summary, 'unknown') AS summary
FROM attachment
WHERE extractor_version = ?1 AND extraction_status = 'failed' ORDER BY safe_filename;

-- statement: repositories/attachments.rs:487
-- params: ["row-0001"]
SELECT count(*) AS total FROM attachment WHERE extractor_version = ?1
AND extraction_status = 'extracted' AND extraction_metadata ->> '$.primaryFailed' = 'true';

-- statement: repositories/attachments.rs:512
-- params: [25]
SELECT id, document_id, gmail_message_id, gmail_part_id, gmail_attachment_id,
       original_filename, mime_type, content_id, is_inline, ordinal, attempts
FROM attachment_download_queue
WHERE status = 'queued' AND attempts < 5
ORDER BY id
LIMIT ?1;

-- statement: repositories/attachments.rs:578
-- params: ["row-0001"]
SELECT id FROM attachment WHERE sha256 = ?1;

-- statement: repositories/attachments.rs:585
-- params: ["row-0001", 1]
UPDATE attachment SET updated_at = ?2 WHERE id = ?1;

-- statement: repositories/attachments.rs:593
-- params: ["row-0001", "row-0001", "row-0001", 1, "row-0001", "row-0001", 1]
INSERT INTO attachment
   (id, sha256, object_path, byte_size, mime_type, safe_filename, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?7);

-- statement: repositories/attachments.rs:611
-- params: ["row-0001", "row-0001", "row-0001", "row-0001", "row-0001", "row-0001", 1, 1]
INSERT INTO message_attachment
   (document_id, attachment_id, gmail_part_id, gmail_attachment_id, content_id,
    original_filename, is_inline, ordinal)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
ON CONFLICT (document_id, attachment_id, ordinal) DO NOTHING;

-- statement: repositories/attachments.rs:629
-- params: [1]
UPDATE attachment_download_queue SET status = 'done', error_summary = NULL WHERE id = ?1;

-- statement: repositories/attachments.rs:644
-- params: [1, "row-0001"]
UPDATE attachment_download_queue
SET attempts = attempts + 1,
    error_summary = ?2,
    status = CASE WHEN attempts + 1 >= 5 THEN 'failed' ELSE 'queued' END
WHERE id = ?1;

-- statement: repositories/attachments.rs:662
-- params: [25]
SELECT id, object_path, mime_type, safe_filename FROM attachment
WHERE extraction_status = 'pending'
ORDER BY created_at LIMIT ?1;

-- statement: repositories/attachments.rs:676
-- params: ["row-0001"]
SELECT COALESCE(min(is_inline), 0) AS is_inline FROM message_attachment
WHERE attachment_id = ?1;

-- statement: repositories/attachments.rs:711
-- params: ["row-0001", "row-0001", "row-0001", "row-0001", "row-0001", "row-0001", 1]
UPDATE attachment
SET extraction_status = ?2, extracted_text = ?3, extractor_version = ?4,
    error_summary = ?5, extraction_metadata = ?6, updated_at = ?7
WHERE id = ?1;

-- statement: repositories/attachments.rs:739
-- params: ["row-0001"]
SELECT e.subject AS subject, e.from_address AS from_address, e.sent_at AS sent_at
FROM message_attachment ma
JOIN email_message e ON e.document_id = ma.document_id
WHERE ma.attachment_id = ?1
ORDER BY e.sent_at IS NULL, e.sent_at
LIMIT 1;

-- statement: repositories/attachments.rs:761
-- params: ["row-0001"]
SELECT object_path, mime_type, safe_filename, byte_size, extraction_status
FROM attachment WHERE id = ?1;

-- statement: repositories/attachments.rs:785
-- params: ["row-0001"]
SELECT safe_filename, extraction_status, extracted_text FROM attachment WHERE id = ?1;

-- statement: repositories/chunks.rs:31
-- params: ["row-0001"]
DELETE FROM chunk WHERE document_id = ?1;

-- statement: repositories/chunks.rs:35
-- params: ["row-0001", "row-0001", 1, "row-0001", "row-0001", "row-0001", 1, "row-0001", "row-0001", 1]
INSERT INTO chunk
   (id, document_id, ordinal, content, heading, locator, char_count, content_hash,
    chunker_version, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10);

-- statement: repositories/chunks.rs:77
-- params: [25]
SELECT c.id AS id, c.content AS content
FROM embedding_queue q
JOIN chunk c ON c.id = q.chunk_id
WHERE c.embedding_attempts < 3
ORDER BY q.queued_at
LIMIT ?1;

-- statement: repositories/chunks.rs:115
-- params: ["row-0001", "row-0001", 1, "[0.1,0.2,0.3,0.4]", 1]
INSERT INTO chunk_embedding (chunk_id, embedding_model, dimension, embedding, indexed_at)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT (chunk_id, embedding_model)
DO UPDATE SET embedding = excluded.embedding, indexed_at = excluded.indexed_at;

-- statement: repositories/chunks.rs:130
-- params: ["row-0001"]
DELETE FROM embedding_queue WHERE chunk_id = ?1;

-- statement: repositories/chunks.rs:134
-- params: ["row-0001"]
UPDATE chunk SET embedding_error = NULL WHERE id = ?1;

-- statement: repositories/chunks.rs:151
-- params: ["row-0001", "row-0001"]
UPDATE chunk SET embedding_attempts = embedding_attempts + 1, embedding_error = ?2 WHERE id = ?1;

-- statement: repositories/chunks.rs:163
-- params: []
SELECT count(*) AS total FROM chunk WHERE embedding_attempts >= 3;

-- statement: repositories/chunks.rs:174
-- params: []
SELECT count(*) AS total FROM embedding_queue q
JOIN chunk c ON c.id = q.chunk_id
WHERE c.embedding_attempts < 3;

-- statement: repositories/corpus.rs:219
-- params: []
SELECT document_id, address, display_name FROM email_participant;

-- statement: repositories/corpus.rs:241
-- params: ["row-0001"]
SELECT document_id, address, display_name FROM email_participant WHERE document_id = ?1;

-- statement: repositories/corpus.rs:291
-- params: []
SELECT id, provider_id FROM document WHERE kind = 'attachment';

-- statement: repositories/corpus.rs:309
-- params: []
SELECT attachment_id, document_id FROM message_attachment;

-- statement: repositories/corpus.rs:350
-- params: []
SELECT kind, id FROM document WHERE deleted_at IS NOT NULL;

-- statement: repositories/documents.rs:32
-- params: ["row-0001", "row-0001"]
SELECT id, content_hash FROM document
WHERE source_account_id = ?1 AND kind = 'email' AND provider_id = ?2;

-- statement: repositories/documents.rs:46
-- params: ["row-0001", "row-0001", "row-0001", "row-0001", "row-0001", "row-0001", 1, 1]
UPDATE document
  SET title = ?2, body_text = ?3, search_body = ?4, raw_source = ?5,
      content_hash = ?6, source_timestamp = ?7, deleted_at = NULL,
      indexed_at = CASE WHEN content_hash = ?6 THEN indexed_at ELSE NULL END,
      updated_at = ?8
WHERE id = ?1;

-- statement: repositories/documents.rs:68
-- params: ["row-0001", "row-0001", "row-0001", "row-0001", "row-0001", "row-0001", "row-0001", "row-0001", 1, 1]
INSERT INTO document
   (id, source_account_id, kind, provider_id, title, body_text, search_body,
    raw_source, content_hash, source_timestamp, deleted_at, indexed_at,
    created_at, updated_at)
VALUES (?1, ?2, 'email', ?3, ?4, ?5, ?6, ?7, ?8, ?9, NULL, NULL, ?10, ?10);

-- statement: repositories/documents.rs:114
-- params: ["row-0001", "row-0001", "row-0001", "row-0001", "row-0001", "row-0001", 1, "row-0001", "row-0001", 1, 1, 1]
INSERT INTO email_message
   (document_id, gmail_thread_id, rfc_message_id, subject, from_name, from_address,
    sent_at, labels, snippet, history_id, size_estimate, has_attachment)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)
ON CONFLICT (document_id) DO UPDATE
SET gmail_thread_id = excluded.gmail_thread_id, rfc_message_id = excluded.rfc_message_id,
    subject = excluded.subject, from_name = excluded.from_name,
    from_address = excluded.from_address, sent_at = excluded.sent_at,
    labels = excluded.labels, snippet = excluded.snippet,
    history_id = excluded.history_id, size_estimate = excluded.size_estimate,
    has_attachment = excluded.has_attachment;

-- statement: repositories/documents.rs:150
-- params: ["row-0001"]
DELETE FROM email_participant WHERE document_id = ?1;

-- statement: repositories/documents.rs:155
-- params: ["row-0001", "row-0001", "row-0001", "row-0001", 1]
INSERT INTO email_participant (document_id, kind, display_name, address, ordinal)
VALUES (?1, ?2, ?3, ?4, ?5);

-- statement: repositories/documents.rs:178
-- params: ["row-0001", "row-0001", "row-0001", "row-0001", "row-0001", "row-0001", "row-0001", 1, 1, 1, 1]
INSERT INTO attachment_download_queue
   (document_id, gmail_message_id, gmail_part_id, gmail_attachment_id, original_filename,
    mime_type, content_id, is_inline, declared_size, ordinal, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11)
ON CONFLICT (document_id, gmail_attachment_id, ordinal) DO NOTHING;

-- statement: repositories/documents.rs:208
-- params: ["row-0001", "row-0001", 1]
UPDATE document SET deleted_at = ?3, updated_at = ?3
WHERE source_account_id = ?1 AND kind = 'email' AND provider_id = ?2;

-- statement: repositories/documents.rs:227
-- params: [25]
SELECT id, source_timestamp FROM document
WHERE indexed_at IS NULL AND deleted_at IS NULL
LIMIT ?1;

-- statement: repositories/documents.rs:248
-- params: ["row-0001", 1]
UPDATE document SET indexed_at = ?2, updated_at = ?2 WHERE id = ?1;

-- statement: repositories/documents.rs:274
-- params: ["row-0001"]
SELECT id, kind, provider_id, title, body_text, search_body, source_timestamp
FROM document WHERE id = ?1;

-- statement: repositories/documents.rs:304
-- params: ["row-0001"]
SELECT gmail_thread_id, subject, from_name, from_address, labels
FROM email_message WHERE document_id = ?1;

-- statement: repositories/documents.rs:312
-- params: ["row-0001"]
SELECT kind, display_name, address FROM email_participant
WHERE document_id = ?1 ORDER BY kind, ordinal;

-- statement: repositories/documents.rs:332
-- params: ["row-0001"]
SELECT a.extracted_text AS extracted_text
FROM document d
JOIN attachment a ON a.id = replace(d.provider_id, 'attachment:', '')
WHERE d.id = ?1 AND d.kind = 'attachment';

-- statement: repositories/documents.rs:393
-- params: ["row-0001"]
SELECT a.id AS id, a.safe_filename AS safe_filename,
       ma.original_filename AS original_filename, a.mime_type AS mime_type,
       a.byte_size AS byte_size, a.extraction_status AS extraction_status,
       ma.is_inline AS is_inline, a.sha256 AS sha256
FROM message_attachment ma
JOIN attachment a ON a.id = ma.attachment_id
WHERE ma.document_id = ?1
ORDER BY ma.ordinal;

-- statement: repositories/documents.rs:412
-- params: ["row-0001"]
SELECT provider_id FROM document WHERE id = ?1 AND kind = 'attachment';

-- statement: repositories/documents.rs:424
-- params: ["row-0001"]
SELECT a.id AS id, a.safe_filename AS safe_filename, a.safe_filename AS original_filename,
       a.mime_type AS mime_type, a.byte_size AS byte_size,
       a.extraction_status AS extraction_status, 0 AS is_inline, a.sha256 AS sha256
FROM attachment a WHERE a.id = ?1;

-- statement: repositories/documents.rs:436
-- params: ["row-0001"]
SELECT original_filename, is_inline FROM message_attachment
WHERE attachment_id = ?1 ORDER BY ordinal LIMIT 1;

-- statement: repositories/documents.rs:472
-- params: ["row-0001"]
SELECT d.id AS document_id, e.subject AS subject, e.from_name AS from_name,
       e.from_address AS from_address, e.sent_at AS sent_at, e.snippet AS snippet,
       (SELECT count(*) FROM message_attachment ma WHERE ma.document_id = d.id) AS attachments
FROM email_message e
JOIN document d ON d.id = e.document_id
WHERE e.gmail_thread_id = ?1 AND d.deleted_at IS NULL
ORDER BY e.sent_at IS NULL, e.sent_at;

-- statement: repositories/documents.rs:521
-- params: ["row-0001", "row-0001"]
SELECT id FROM document
WHERE source_account_id = ?1 AND kind = 'attachment' AND provider_id = ?2;

-- statement: repositories/documents.rs:529
-- params: ["row-0001", "row-0001", "row-0001", "row-0001", 1, 1]
UPDATE document
  SET title = ?2, body_text = ?3, search_body = ?3, content_hash = ?4,
      source_timestamp = ?5, deleted_at = NULL,
      indexed_at = CASE WHEN content_hash = ?4 THEN indexed_at ELSE NULL END,
      updated_at = ?6
WHERE id = ?1;

-- statement: repositories/documents.rs:549
-- params: ["row-0001", "row-0001", "row-0001", "row-0001", "row-0001", "row-0001", 1, 1]
INSERT INTO document
   (id, source_account_id, kind, provider_id, title, body_text, search_body,
    content_hash, source_timestamp, indexed_at, created_at, updated_at)
VALUES (?1, ?2, 'attachment', ?3, ?4, ?5, ?5, ?6, ?7, NULL, ?8, ?8);

-- statement: repositories/documents.rs:579
-- params: ["row-0001", "row-0001", 1]
UPDATE document SET deleted_at = ?3, updated_at = ?3
WHERE source_account_id = ?1 AND kind = 'attachment' AND provider_id = ?2;

-- statement: repositories/documents.rs:594
-- params: ["row-0001", "row-0001"]
DELETE FROM chunk WHERE document_id IN (
SELECT id FROM document
WHERE source_account_id = ?1 AND kind = 'attachment' AND provider_id = ?2);

-- statement: repositories/documents.rs:614
-- params: ["row-0001", "row-0001", "row-0001", "row-0001", "row-0001", 1, 1]
INSERT INTO document_meta
   (document_id, kind, from_address, from_name, labels, thread_id, has_attachment, sent_at)
VALUES (?1, 'email', ?2, ?3, ?4, ?5, ?6, ?7)
ON CONFLICT (document_id) DO UPDATE
SET from_address = excluded.from_address, from_name = excluded.from_name,
    labels = excluded.labels, thread_id = excluded.thread_id,
    has_attachment = excluded.has_attachment, sent_at = excluded.sent_at;

-- statement: repositories/documents.rs:645
-- params: ["row-0001"]
SELECT from_address, from_name, labels, thread_id, sent_at
FROM document_meta WHERE document_id = ?1;

-- statement: repositories/documents.rs:651
-- params: ["row-0001", "row-0001", "row-0001", "row-0001", "row-0001", 1]
INSERT INTO document_meta
   (document_id, kind, from_address, from_name, labels, thread_id, has_attachment, sent_at)
VALUES (?1, 'attachment', ?2, ?3, ?4, ?5, 1, ?6)
ON CONFLICT (document_id) DO UPDATE
SET from_address = excluded.from_address, from_name = excluded.from_name,
    labels = excluded.labels, thread_id = excluded.thread_id,
    sent_at = excluded.sent_at;

-- statement: repositories/documents.rs:670
-- params: ["row-0001"]
INSERT INTO document_meta (document_id, kind, has_attachment)
VALUES (?1, 'attachment', 1) ON CONFLICT (document_id) DO NOTHING;

-- statement: repositories/search.rs:58
-- params: [1]
SELECT d.id AS document_id, d.kind AS kind, d.title AS title,
       substr(d.body_text, 1, 300) AS body_snippet,
       m.from_name AS from_name, m.from_address AS from_address, m.sent_at AS sent_at,
       m.labels AS labels, m.thread_id AS thread_id,
       (SELECT count(*) FROM message_attachment ma WHERE ma.document_id = d.id)
           AS attachment_count
FROM document d
JOIN document_meta m ON m.document_id = d.id
WHERE d.id = ?1;

-- statement: repositories/search.rs:74
-- params: ["row-0001"]
SELECT snippet FROM email_message WHERE document_id = ?1;

-- statement: repositories/search.rs:112
-- params: ["row-0001"]
SELECT document_id, address FROM email_participant
WHERE document_id = ?1 AND kind IN ('to', 'cc') ORDER BY kind, ordinal;

-- statement: repositories/status.rs:46
-- params: []
SELECT provider_account, authorization_state FROM source_account
WHERE source_type = 'gmail' LIMIT 1;

-- statement: repositories/status.rs:56
-- params: []
SELECT messages_total_remote, last_history_id, full_sync_started_at,
       full_sync_completed_at, last_incremental_at
FROM gmail_sync_state LIMIT 1;

-- statement: repositories/status.rs:77
-- params: []
SELECT count(*) AS total FROM document WHERE kind = 'email' AND deleted_at IS NULL;

-- statement: repositories/status.rs:78
-- params: []
SELECT count(*) AS total FROM document WHERE kind = 'email' AND deleted_at IS NOT NULL;

-- statement: repositories/status.rs:79
-- params: []
SELECT count(*) AS total FROM document WHERE kind = 'attachment';

-- statement: repositories/status.rs:80
-- params: []
SELECT count(*) AS total FROM attachment;

-- statement: repositories/status.rs:81
-- params: []
SELECT count(*) AS total FROM attachment_download_queue WHERE status = 'queued';

-- statement: repositories/status.rs:82
-- params: []
SELECT count(*) AS total FROM attachment WHERE extraction_status = 'pending';

-- statement: repositories/status.rs:83
-- params: []
SELECT count(*) AS total FROM attachment WHERE extraction_status = 'failed';

-- statement: repositories/status.rs:84
-- params: []
SELECT count(*) AS total FROM attachment_download_queue WHERE status = 'failed';

-- statement: repositories/status.rs:85
-- params: []
SELECT count(*) AS total FROM chunk;

-- statement: repositories/status.rs:108
-- params: ["row-0001"]
SELECT count(*) AS total FROM chunk_embedding WHERE embedding_model = ?1;

-- statement: repositories/status.rs:219
-- params: []
SELECT count(*) AS total FROM document WHERE indexed_at IS NULL AND deleted_at IS NULL;

-- statement: repositories/status.rs:306
-- params: []
SELECT id, job_type, status, counters, error_summary, started_at, finished_at
FROM sync_job WHERE status = 'running' ORDER BY id DESC LIMIT 1;

-- statement: repositories/status.rs:320
-- params: []
SELECT id, job_type, status, counters, error_summary, started_at, finished_at
FROM sync_job ORDER BY id DESC LIMIT 10;

-- statement: repositories/status.rs:340
-- params: []
SELECT labels FROM document_meta WHERE kind = 'email';

-- statement: repositories/users.rs:24
-- params: ["row-0001"]
SELECT username, display_name, role, password_hash FROM app_user WHERE username = ?1;

-- statement: repositories/users.rs:48
-- params: ["row-0001", "row-0001", "row-0001", "row-0001", 1]
INSERT INTO app_user (username, display_name, role, password_hash, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?5)
ON CONFLICT (username) DO UPDATE
  SET display_name = excluded.display_name,
      role = excluded.role,
      password_hash = excluded.password_hash,
      updated_at = excluded.updated_at;

-- statement: repositories/users.rs:66
-- params: []
SELECT username, display_name, role FROM app_user ORDER BY username;

-- statement: repositories/users.rs:83
-- params: ["row-0001", "row-0001", 1, 1]
INSERT INTO app_session (token_sha256, username, created_at, last_seen_at, expires_at)
VALUES (?1, ?2, ?3, ?3, ?4);

-- statement: repositories/users.rs:110
-- params: ["row-0001", 1]
SELECT u.username AS username, u.display_name AS display_name, u.role AS role
 FROM app_session s
 JOIN app_user u ON u.username = s.username
WHERE s.token_sha256 = ?1 AND s.expires_at > ?2;

-- statement: repositories/users.rs:120
-- params: ["row-0001", 1, 1]
UPDATE app_session SET last_seen_at = ?2, expires_at = ?3 WHERE token_sha256 = ?1;

-- statement: repositories/users.rs:137
-- params: ["row-0001"]
DELETE FROM app_session WHERE token_sha256 = ?1;

-- statement: repositories/users.rs:145
-- params: [1]
DELETE FROM app_session WHERE expires_at <= ?1;

-- statement: repositories/users.rs:162
-- params: ["row-0001"]
SELECT username FROM agent_session WHERE session_id = ?1;

-- statement: repositories/users.rs:171
-- params: ["row-0001", 1]
UPDATE agent_session SET last_used_at = ?2 WHERE session_id = ?1;

-- statement: repositories/users.rs:178
-- params: ["row-0001", "row-0001", 1]
INSERT INTO agent_session (session_id, username, created_at, last_used_at)
VALUES (?1, ?2, ?3, ?3);

-- statement: services/adopt.rs:357
-- params: ["row-0001", "row-0001", "row-0001", "row-0001", "row-0001", 1, 1]
INSERT INTO source_account
   (id, source_type, provider_account, display_name, authorization_state, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7);

-- statement: services/adopt.rs:385
-- params: ["row-0001", 1, "row-0001", 1, 1, 1, 1, 1]
INSERT INTO gmail_sync_state
   (source_account_id, last_history_id, full_sync_page_token, full_sync_started_at,
    full_sync_completed_at, last_incremental_at, messages_total_remote, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8);

-- statement: services/adopt.rs:415
-- params: ["row-0001", "row-0001", "row-0001", "row-0001", "row-0001", "row-0001", "row-0001", "row-0001", "row-0001", 1, 1, 1, 1, 1]
INSERT INTO document
   (id, source_account_id, kind, provider_id, title, body_text, search_body, raw_source,
    content_hash, source_timestamp, deleted_at, indexed_at, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14);

-- statement: services/adopt.rs:451
-- params: ["row-0001", "row-0001", "row-0001", "row-0001", "row-0001", "row-0001", 1, "row-0001", "row-0001", 1, 1, 1]
INSERT INTO email_message
   (document_id, gmail_thread_id, rfc_message_id, subject, from_name, from_address, sent_at,
    labels, snippet, history_id, size_estimate, has_attachment)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12);

-- statement: services/adopt.rs:484
-- params: [1, "row-0001", "row-0001", "row-0001", "row-0001", 1]
INSERT INTO email_participant (id, document_id, kind, display_name, address, ordinal)
VALUES (?1, ?2, ?3, ?4, ?5, ?6);

-- statement: services/adopt.rs:510
-- params: ["row-0001", "row-0001", "row-0001", 1, "row-0001", "row-0001", "row-0001", "row-0001", "row-0001", "row-0001", 1, 1, "row-0001"]
INSERT INTO attachment
   (id, sha256, object_path, byte_size, mime_type, safe_filename, extraction_status,
    extracted_text, extractor_version, error_summary, created_at, updated_at, extraction_metadata)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13);

-- statement: services/adopt.rs:545
-- params: [1, "row-0001", "row-0001", "row-0001", "row-0001", "row-0001", "row-0001", 1, 1]
INSERT INTO message_attachment
   (id, document_id, attachment_id, gmail_part_id, gmail_attachment_id, content_id,
    original_filename, is_inline, ordinal)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9);

-- statement: services/adopt.rs:577
-- params: [1, "row-0001", "row-0001", "row-0001", "row-0001", "row-0001", "row-0001", "row-0001", 1, 1, 1, "row-0001", 1, "row-0001", 1]
INSERT INTO attachment_download_queue
   (id, document_id, gmail_message_id, gmail_part_id, gmail_attachment_id, original_filename,
    mime_type, content_id, is_inline, declared_size, ordinal, status, attempts, error_summary,
    created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15);

-- statement: services/adopt.rs:615
-- params: ["row-0001", "row-0001", 1, "row-0001", "row-0001", "row-0001", 1, "row-0001", "row-0001", 1, 1, "row-0001"]
INSERT INTO chunk
   (id, document_id, ordinal, content, heading, locator, char_count, content_hash,
    chunker_version, created_at, embedding_attempts, embedding_error)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12);

-- statement: services/adopt.rs:652
-- params: ["row-0001", "row-0001", 1, "[0.1,0.2,0.3,0.4]", 1]
INSERT INTO chunk_embedding (chunk_id, embedding_model, dimension, embedding, indexed_at)
VALUES (?1, ?2, ?3, ?4, ?5);

-- statement: services/adopt.rs:679
-- params: ["row-0001", "row-0001", "row-0001", "row-0001", "row-0001", "row-0001", 1, 1]
INSERT INTO document_meta
   (document_id, kind, from_address, from_name, labels, thread_id, has_attachment, sent_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8);

-- statement: services/adopt.rs:708
-- params: [1, "row-0001", "row-0001", "row-0001", "row-0001", "row-0001", 1, "row-0001", 1, 1, 1, 1]
INSERT INTO sync_job
   (id, source_account_id, job_type, status, counters, checkpoint, attempts, error_summary,
    started_at, finished_at, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12);

-- statement: services/adopt.rs:741
-- params: ["row-0001", "row-0001", "row-0001", "row-0001", 1, 1]
INSERT INTO app_user (username, display_name, role, password_hash, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6);

-- statement: services/adopt.rs:766
-- params: ["row-0001", "row-0001", 1, 1, 1]
INSERT INTO app_session (token_sha256, username, created_at, last_seen_at, expires_at)
VALUES (?1, ?2, ?3, ?4, ?5);

-- statement: services/adopt.rs:790
-- params: ["row-0001", "row-0001", 1, 1]
INSERT INTO agent_session (session_id, username, created_at, last_used_at)
VALUES (?1, ?2, ?3, ?4);

-- statement: services/adopt.rs:829
-- params: ["row-0001"]
-- inferred: slot 1 stands beside no column this schema declares
SELECT COALESCE(seq, 0) AS seq FROM sqlite_sequence WHERE name = ?1;

-- statement: services/adopt.rs:853
-- params: ["row-0001", "row-0001", 1]
INSERT INTO sync_job (job_type, status, counters, started_at, finished_at, created_at, updated_at)
VALUES ('adopt-inillucent', ?1, ?2, ?3, ?3, ?3, ?3);

-- statement: services/bench.rs:66
-- params: [25]
SELECT id FROM document WHERE deleted_at IS NULL AND kind = 'email'
ORDER BY content_hash LIMIT ?1;

-- statement: services/bench.rs:73
-- params: [25]
SELECT gmail_thread_id AS id FROM email_message GROUP BY gmail_thread_id
ORDER BY gmail_thread_id LIMIT ?1;

-- statement: services/bench.rs:80
-- params: [25]
SELECT id FROM document WHERE kind = 'attachment' ORDER BY content_hash LIMIT ?1;

-- statement: services/bench.rs:250
-- params: ["row-0001"]
SELECT a.id FROM message_attachment ma JOIN attachment a ON a.id = ma.attachment_id
WHERE ma.document_id = ?1;

-- statement: services/bench.rs:264
-- params: ["row-0001"]
SELECT d.id, e.subject, e.sent_at,
       (SELECT count(*) FROM message_attachment ma WHERE ma.document_id = d.id) AS attachments
FROM email_message e JOIN document d ON d.id = e.document_id
WHERE e.gmail_thread_id = ?1 AND d.deleted_at IS NULL
ORDER BY e.sent_at IS NULL, e.sent_at;

-- statement: services/bench.rs:281
-- params: ["row-0001"]
SELECT a.extracted_text FROM document d
JOIN attachment a ON a.id = replace(d.provider_id, 'attachment:', '')
WHERE d.id = ?1 AND d.kind = 'attachment';

-- statement: services/bench.rs:297
-- params: ["row-0001"]
SELECT (SELECT count(*) FROM document WHERE kind='email' AND deleted_at IS NULL) AS a,
(SELECT count(*) FROM document WHERE deleted_at IS NOT NULL) AS b,
(SELECT count(*) FROM chunk) AS c,
(SELECT count(*) FROM chunk_embedding WHERE embedding_model = ?1) AS d,
(SELECT count(*) FROM attachment WHERE extraction_status='pending') AS e;

-- statement: services/gates.rs:764
-- params: []
SELECT from_name AS value FROM document_meta
WHERE from_name IS NOT NULL AND from_name <> ''
GROUP BY from_name ORDER BY count(*) DESC LIMIT 1;

-- statement: services/gates.rs:777
-- params: []
SELECT thread_id AS value FROM document_meta WHERE thread_id IS NOT NULL
GROUP BY thread_id ORDER BY count(*) DESC LIMIT 1;

-- statement: services/gates.rs:786
-- params: []
SELECT address AS value FROM email_participant
GROUP BY address ORDER BY count(*) DESC LIMIT 1;

-- statement: services/gates.rs:867
-- params: ["row-0001"]
SELECT d.id AS id, d.kind AS kind, d.provider_id AS provider_id,
       m.from_address AS from_address, m.from_name AS from_name, m.labels AS labels,
       m.thread_id AS thread_id, m.sent_at AS sent_at, m.has_attachment AS has_attachment
FROM document d
JOIN document_meta m ON m.document_id = d.id
WHERE d.id = ?1 AND d.deleted_at IS NULL;

-- statement: services/gates.rs:945
-- params: ["row-0001"]
SELECT ma.document_id AS document_id FROM message_attachment ma
WHERE ma.attachment_id = ?1 LIMIT 1;

-- statement: services/gates.rs:956
-- params: ["row-0001"]
SELECT address, display_name FROM email_participant WHERE document_id = ?1;

-- statement: services/ingestion.rs:506
-- params: ["row-0001"]
SELECT from_address, from_name, sent_at FROM document_meta WHERE document_id = ?1;

-- statement: services/ingestion.rs:529
-- params: ["row-0001"]
SELECT e.subject AS subject, a.mime_type AS mime_type
FROM attachment a
JOIN message_attachment ma ON ma.attachment_id = a.id
JOIN email_message e ON e.document_id = ma.document_id
WHERE a.id = ?1
ORDER BY e.sent_at IS NULL, e.sent_at
LIMIT 1;

-- statement: services/ingestion.rs:555
-- params: ["row-0001"]
SELECT address FROM email_participant
WHERE document_id = ?1 AND kind IN ('to','cc') ORDER BY ordinal LIMIT 12;

-- statement: services/ingestion.rs:707
-- params: ["row-0001", 1]
INSERT INTO sync_job (job_type, status, started_at, created_at, updated_at)
VALUES (?1, 'running', ?2, ?2, ?2) RETURNING id;

-- statement: services/ingestion.rs:720
-- params: [1, "row-0001", 1]
UPDATE sync_job SET counters = ?2, updated_at = ?3 WHERE id = ?1;

-- statement: services/ingestion.rs:730
-- params: [1, "row-0001", "row-0001", 1]
UPDATE sync_job SET status = ?2, error_summary = ?3, finished_at = ?4, updated_at = ?4
WHERE id = ?1;

-- statement: services/ingestion.rs:741
-- params: []
SELECT count(*) AS total FROM sync_job WHERE status = 'running';

-- statement: services/verify.rs:106
-- params: []
SELECT count(*) AS total FROM sync_job
WHERE job_type <> 'adopt-inillucent'
  AND started_at > (SELECT max(started_at) FROM sync_job WHERE job_type = 'adopt-inillucent');

-- statement: services/verify.rs:142
-- params: []
SELECT count(*) AS total FROM sync_job WHERE job_type = 'adopt-inillucent';

